### ISSUE TITLE
Card got stuck in revealed zone during Near Field Comm

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1048]
![Uploading Screen Shot 2023-05-01 at 10.12.58 PM.png…]()

**Comment by micahstairs** [comment]
I'm unable to replicate this. If this happens again, we should take note of which card was executed.

**Comment by ultimatefiend** [comment]
did you use a demand card like componentization?

**Comment by micahstairs** [comment]
Never heard of that card before hehe

**Comment by ultimatefiend** [comment]
Haha, composites...woops. :)

**Comment by micahstairs** [comment]
Oh nice, I was able to replicate with Composites.

**Comment by micahstairs** [comment]
Oh specifically that's happening because Composites has no non-demand effects.
