### ISSUE TITLE
Add support for revealing a player's hand

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#105]
There are several Artifact cards which require a player to reveal their hand. Instead of moving cards one by one to the revealed zone and back again (which could take a lot of time and also make it hard for players know what was revealed if they miss the animation), we should instead dump out a card list in the log.

Here are some example dogma effects which reveal a player's hand:

```Choose a number and a color. Draw five ${age_4}, then reveal your hand. If you have exactly that many cards of that color, score them, and splay right your cards of that color. Otherwise, return all cards from your hand. ```

``` Reveal your hand. If you have exactly five cards and five colors in your hand, you win. ```

In addition to dumping the card names in the log, we likely want to try to make a few other improvements to card names in the logs:
- Hovering over a card name should show a tooltip.
- The card name should be colored based on the card's color (if this actually looks good). Here are the hex values for the 5 colors: Blue: #0e2a50, Red: #5a090c, Green: #122c18, Yellow #8b6a28, Purple: #220e40.
- Make capitalization consistent across cards (maybe capitalize every letter if it looks good?). This has to be accomplished using `.toUpperCase()` in the JavaScript code after being translated (as opposed to modifying the original strings which would mess up translations).

Once this is implemented, we'd also like to make the Oars card reveal a hand if they don't have any card in their hand with a coin, as requested by Chris in https://boardgamearena.com/bug?id=36171.

**Comment by ultimatefiend** [comment]
Mjolnir (age 3) throws a monkey wrench into this plan because the compel effect allows the executor to choose a card (and meld) a card from their opponent's hand.

**Comment by micahstairs** [comment]
I guess we will just have to handle that case differently. We can't move those cards to the revealed area anyway because not everyone is supposed to see the cards.

That makes me wonder about Oars. Who gets to see the player's hand? Just the person playing Oars?

**Comment by jacksonmead** [comment]
Text of Moylough Belt Shrine: "I COMPEL you to reveal all cards in your hand and transfer the card of my choice to my board!" It doesn't say anything about only revealing it to one person.

**Comment by micahstairs** [comment]
So whenever we explicitly see that "reveal" keyword we know that all players get to see it.

**Comment by ultimatefiend** [comment]
Yeah, I agree.  Reveal is public knowledge.  If the card said to transfer to the player's hand, then it would be private.

**Comment by micahstairs** [comment]
I wonder if a solution to this problem would be to just accelerate the speed of the animation when we are moving around lots of cards (e.g. 5 or more)? This would be useful in other situations too.

**Comment by ultimatefiend** [comment]
Yes I think that would be great.

**Comment by ultimatefiend** [comment]
Maybe transfer 3 cards at a time?

**Comment by micahstairs** [comment]
I suspect that trying to move around multiple cards at once will break things!

**Comment by ultimatefiend** [comment]
what if the cards were revealed the same way the cards in your score are revealed when you click on score or when you are prompted to do something with your score pile?

Twister (age 10) says to reveal your score pile so that is a similar problem to this.

**Comment by micahstairs** [comment]
We've decide to defer these "enhancements" until later. For now, we can just move cards one at a time.

**Comment by micahstairs** [comment]
I think we should probably prioritize this work, since this would greatly improve the user experience of certain artifact cards.

To clarify, I'm proposing we dump the cards out to the game log (as opposed to moving cards more quickly or moving multiple at a time). There are a number of tasks here, so it will likely be worth splitting some of them out into other issues (e.g. "Hovering over a card name should show a tooltip" could be a separate bug).

**Comment by micahstairs** [comment]
"Mask of Warka" could also benefit from this bulk reveal.

**Comment by micahstairs** [comment]
The functionality is added:

<img width="692" alt="Screen Shot 2022-02-28 at 7 48 40 PM" src="https://user-images.githubusercontent.com/7231485/156084316-0d49584f-0ae9-488b-88cd-19a622fb2958.png">

I'll close this and then I'll file separate issues for each of the cards which need to be updated.
