### ISSUE TITLE
Can you choose to pick a value for Fusion such that you don't score something?

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#1053]
i.e., You score an 11, and then you have a 10 as atop card but not a 9. Can you choose to do 2 less rather than 1 less and therefore not score anything? And either way, are there wording tweaks that can be made to make it explicit which one is the case?

**Comment by micahstairs** [comment]
Thanks! I just sent an email.

**Comment by ultimatefiend** [comment]
@jacksonmead from Carl: "You can choose a value for which you do not have a top card to score. How about

Score a top card of value 11 on your board.  If you do, choose a value one or two lower than the scored card, then repeat this dogma effect using the chosen value."
