### ISSUE TITLE
Construction still gave Empire achievement when the specials had been junked (Ultimate)

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#1057]

**Comment by ultimatefiend** [comment]
I bet the special achievements aren't considering where the achievements are coming from

**Comment by ultimatefiend** [comment]
if ($achievement['owner'] == 0 && $achievement['location'] != 'removed') {

Yup that's it.  'junk' needs to be a part of that check

**Comment by micahstairs** [comment]
I just did a broader fix to fix all 10 special achievements.
