### ISSUE TITLE
Empire not awarded correctly

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#1058]
https://studio.boardgamearena.com/1/innovationdev?table=479085, move 100

**Comment by ultimatefiend** [comment]
![image](https://user-images.githubusercontent.com/11416698/236118237-ea2b2b89-197d-4a92-a6b9-23b5c50f66f1.png)

**Comment by ultimatefiend** [comment]
foreach (self::getPlayerResourceCounts($player_id) as $icon => $count) {
                    if ($count >= 3) {
                        $num_resources_with_three_or_more++;
                        break;
                    }
                }

Why is that break there?
