### ISSUE TITLE
Space Traffic kept repeating when it shouldn't have

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#1060]
My opponent dogmaed Space Traffic, and I shared. It kept repeating even once my score was higher than my opponent's. At the beginning of the log in the screenshot below, I had a score of 20 and my opponent had 38. So after it did the dogma effect twice, I had a higher score, and it should have stopped, but it just kept going until the 11s ran out.

<img width="163" alt="Screen Shot 2023-05-04 at 7 25 41 PM" src="https://user-images.githubusercontent.com/15677300/236350724-f8ee10b9-95f6-4705-880d-092607701267.png">

**Comment by ultimatefiend** [comment]
I think this logic needs to avoid the executing player in the loop:

                    foreach (self::getAllActivePlayerIds() as $players) {
                        if (self::getPlayerScore($players) > $player_score)  {
                            $keep_going = true;
                        }
                    }

**Comment by ultimatefiend** [comment]
and $keep_going needs to be reset inside the loop:

                $keep_going = false;
                do {
                    // "Draw and tuck an 11."
                    $card = self::executeDraw($player_id, 11);

**Comment by micahstairs** [comment]
We don't need to skip the current player (since X is never larger than X), but yes, you're right that the bug was there.
