### ISSUE TITLE
Machinery didn't do 2nd non-demand effect (Ultimate)

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#1061]
Machinery executed the demand effect and then the first non-demand effect, but then the log said "You have to execute the 2nd non-demand effect." but it didn't allow me to splay my reds left.

**Comment by ultimatefiend** [comment]
there is no second effect:

            case "31N1_4E":
                $has_card_with_tower = false;
                foreach (self::getCardsInLocation($player_id, 'hand') as $card) {
                    if (self::hasRessource($card, 4 /* tower */)) {
                        $has_card_with_tower = true;
                        break;
                    }
                }
                if ($has_card_with_tower) {
                    $step_max = 1;
                } else {
                    self::revealHand($player_id);
                    self::notifyPlayer($player_id, 'log', clienttranslate('${You} have no cards with a ${tower} in your hand.'), array('You' => 'You', 'tower' => $tower));
                    self::notifyAllPlayersBut($player_id, 'log', clienttranslate('${player_name} has no cards with a ${tower} in his hand.'), array('player_name' => self::getColoredPlayerName($player_id), 'tower' => $tower));
                }
                break;
                
            // id 32, age 3: Medicine        
            case "32D1":
                $step_max = 2;
                break;
