### ISSUE TITLE
Flight causing error

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1062]
Server syntax error:
Notice: Trying to access array offset on value of type null in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 9066
{"status":1,"data":{"valid":1,"data":null}}

**Comment by ultimatefiend** [comment]
I think it might be this check:

        // Many cards do not have a demand effect on them
        if (self::getDemandEffect($card['id']) == null) {
            return true;
        }

There were no red cards on my opponent's board when i shared flight.

**Comment by micahstairs** [comment]
Actually I think it's on line 9066 like the error says:

if ($top_red_card['splay_direction'] != 3 && !in_array(1 /* red */, $up_splayable_colors)) {

**Comment by ultimatefiend** [comment]
nice

**Comment by ultimatefiend** [comment]
I guess that was present before
