### ISSUE TITLE
Distance sharing rule isn't working correctly (Ultimate)

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#1064]
See our 4p game. jacksonmeads dogmaed Metalworking, but then this is what happened with the log (Micah was the player who was far from jacksonmeads and needed to discard to share):

<img width="171" alt="Screen Shot 2023-05-10 at 5 56 56 PM" src="https://github.com/micahstairs/bga-innovation/assets/15677300/b45b9ed7-5b5a-49a5-9b34-a43e2fa56b0d">

So basically, it treated it as if it were Micah's dogma and made both Micah and jacksonmeads discard to share.

**Comment by ultimatefiend** [comment]
Micah shouldn't be sharing metalworking.  he has leaves and not castles.

**Comment by micahstairs** [comment]
Actually, I used the distance rule to invoke Metalworking. And then later Jackson used the distance rule to share it from me.

**Comment by ultimatefiend** [comment]
you can invoke other people's cards?

**Comment by micahstairs** [comment]
Yup! You can return a card from hand in order to dogma a non-adjacent player's top card.

**Comment by ultimatefiend** [comment]
woah, will definitely try that.  that's a little mindblowing

**Comment by ultimatefiend** [comment]
but it still shares with everyone?

**Comment by micahstairs** [comment]
It's like a normal dogma, yeah.

**Comment by micahstairs** [comment]
I checked with Carl and he confirmed this is working as expected.
