### ISSUE TITLE
Monotheism automation not working in Ultimate

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#1065]
In our 4p game, I dogmaed Monotheism, but it didn't automate the transfer of a card when my opponent had only one card to transfer.

**Comment by micahstairs** [comment]
Hmm I wasn't able to replicate this in the studio. And I highly doubt this has anything to do with the number of players in the game. The logic is very generic for this.

We will have to keep an eye out to see if it happens again. Maybe we can spot a pattern.

**Comment by madisonsilver** [comment]
Got it on move 1 of https://boardgamearena.com/2/innovationalpha?table=376421396 .  
![image](https://github.com/micahstairs/bga-innovation/assets/24858452/85208f0d-ec5f-414c-aedf-e53cf9615e64)

**Comment by micahstairs** [comment]
Also happened with Skyscrapers.

**Comment by micahstairs** [comment]
Maybe we are not unselecting cards in hand after the parley choice of the previous player?

**Comment by micahstairs** [comment]
Fixed!
