### ISSUE TITLE
Add Unseen cards to materials file

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1073]
Numbering starts at 480 (and we put them in order of blue, red, green, yellow, purple in ascending order of age).

**Comment by micahstairs** [comment]
The cards are listed here: https://docs.google.com/spreadsheets/d/1LZb7f99F3cdEtGpy39xFiIapnQkH_5Lk_FhgyQn04Do/edit#gid=2061551560.

**Comment by micahstairs** [comment]
The existing materials file is here: https://github.com/micahstairs/bga-innovation/blob/main-4/material.inc.php. You can look at the existing cards to understand the structure. You won't need to worry about any `_first_and_third` or `_fourth` suffixes since all of the Unseen cards are fourth edition anyway.

**Comment by jacksonmead** [comment]
Here's the materials file with Unseen Age 1 in it (with the extension ".txt" appended because I can't attach a .php file).
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11473616/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 2 materials file. 
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11481925/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 3 materials file.
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11497708/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 4 materials file (and not I fixed an unescaped apostrophe in Age 1).
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11524571/material.inc.php.txt)

**Comment by ultimatefiend** [comment]
Don't bother with the special achievements.  I put them in there already

**Comment by jacksonmead** [comment]
Unseen Age 5 materials file.
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11638627/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 6 materials file.
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11706810/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 7 materials file.
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11779211/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 8 materials file.
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11792616/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unessn Age 9 materials file. Depending on response form Carl, may need to make changes to Scouting (Age 8) and Fermi Paradox (Age 9).
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11842994/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 10 materials file.
[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11887798/material.inc.php.txt)

**Comment by jacksonmead** [comment]
Unseen Age 11 materials file.

[material.inc.php.txt](https://github.com/micahstairs/bga-innovation/files/11900033/material.inc.php.txt)
