### ISSUE TITLE
Icon matching functions don't consider spot_6

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1088]
WHERE
                a.owner = {player_id} AND
                a.location = 'board' AND
                a.position = b.position AND
                (a.spot_1 = {icon} OR a.spot_2 = {icon} OR a.spot_3 = {icon} OR a.spot_4 = {icon})

**Comment by micahstairs** [comment]
Oh this explains https://en.boardgamearena.com/bug?id=88035. Nice find!

**Comment by micahstairs** [comment]
I'm just going to fix this in our ongoing alpha and it will eventually get deployed to production (probably at the end of the year, but this hasn't been causing very many issues in production it seems).
