### ISSUE TITLE
Add support for splaying any pile

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#109]
Right now the mechanism to choose a pile to splay assumes that you are only splaying your own piles. There is at least one card in the Artifact expansion ("Cyrus Cylinder") which lets you splay any player's pile. I believe this will require a fairly significant change in order to add support for this. We should make this change carefully to avoid adding too much complexity to the code.

**Comment by ultimatefiend** [comment]
There is an echoes card that does it that is super annoying.  Its a red age 4 card.
