### ISSUE TITLE
Self-Service/Near-Field Comms/Escapism can cause infinite loops

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#1090]
Under certain conditions, it's possible to for the above self-execute cards to activate each other and trigger a mandatory infinite loop.  (e.g having Self-Service in hand, Escapism on board, and no other cards)  This makes the server respond with an "Unable to contact the server." error whenever the loop is triggered.  (This can also be done maliciously, by sharing the effect with an opponent, forcing them to take an action, then locking out the game when they try to finish their dogma.)

See e.g https://studio.boardgamearena.com/1/innovationdev?table=479339

**Comment by micahstairs** [comment]
Thanks for flagging! I started a discussion with Carl and Chris about this.

**Comment by micahstairs** [comment]
The Chain Rule resolved this.
