### ISSUE TITLE
Create a second expandable auxiliary array

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1098]
Some cards require storing multiple large arrays such as polytheism needing a card id array and a color count array.

**Comment by micahstairs** [comment]
Many of these cards need an auxiliary array which only gets reset at the end of each action (e.g. Polytheism, Legend, Dancing Girl, Democracy). So we will want it to be keyed by card ID and player at least.

**Comment by micahstairs** [comment]
Maze needs something similar but it can't be action-scoped.

**Comment by micahstairs** [comment]
Oh I don't think Maze needs this after all! I'll give that card a shot. Never mind, it will work nicer with this array.
