### ISSUE TITLE
Transferring from junk to hand leads to weird rendering

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1129]
It doesn't draw the cards right unless you refresh the page.

![image](https://github.com/micahstairs/bga-innovation/assets/11416698/3efd6e28-7813-4fec-a6b3-273e03a74546)

**Comment by ultimatefiend** [comment]
Yes, the interface gets unstable when this happens.  This might be the issue with fermi as well.
https://boardgamearena.com/bug?id=92476

**Comment by micahstairs** [comment]
I suspect this is a frontend bug, but it's possible the backend is not passing all of the info that the front end needs.
