### ISSUE TITLE
[Ultimate Dev] Symbology not drawing correctly

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#1133]
https://studio.boardgamearena.com/table?table=499160, move ~6.  MadisonSilver1 has 3 leaves and 2 lightbulbs, which should let them draw a 2 off of symbology, but the dogma doesn't do anything.

**Comment by ultimatefiend** [comment]
foreach (self::getPlayerResourceCounts($player_id) as $icon => $count) {
                    if ($count >= 4) {
                        $num_resources_four_or_more++;
                        $num_resources_three_or_more++;
                        $num_resources_two_or_more++;
                    } elseif($count >= 3) {
                        $num_resources_three_or_more++;
                        $num_resources_two_or_more++;
                    } elseif($count >= 2) {
                        $num_resources_two_or_more++;
                    }
                }
                
                if ($num_resources_four_or_more >= 4) {
                    // "If you have four each of four icons on your board, draw a 4."
                    self::executeDraw($player_id, 4);
                } elseif ($num_resources_four_or_more >= 3) {
                    // "Otherwise, if you have three each of three icons on your board, draw a 3."
                    self::executeDraw($player_id, 3);
                } elseif ($num_resources_four_or_more >= 2) {
                    // "Otherwise, if you have two each of two icons on your board, draw a 2."
                    self::executeDraw($player_id, 2);
                }
                
                $num_resources_four_or_more  appears too many times on the bottom elseifs.

**Comment by ultimatefiend** [comment]
The top part can be simplified by making 3 different if's instead of using elseif:

if ($count >= 4) {
                    $num_resources_four_or_more++;
                 }
                if($count >= 3) {
                    $num_resources_three_or_more++;
                } 
if($count >= 2) {
                    $num_resources_two_or_more++;
                }

**Comment by micahstairs** [comment]
The bug was that we were using `num_resources_four_or_more` in all three spots in the bottom.
