### ISSUE TITLE
Add lattice to card backgrounds

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#114]
Here's what Chris thought when I showed him the cards without the lattice:
```I don't think the cards look as good without the full lattice, but I know that's a pretty big challenge to add, so it's not as big of a deal. It's probably not worth the time it would take to implement, although if someone is looking for a project to do, it might be worth it.```

My main concern here is that we don't want to have 10x the number of card background images because that will use a lot of space. Another concern is that some of the backgrounds will be non-trivial to regenerate (since we need to regenerate the pattern appearing underneath the icons). Perhaps we could find a way to make a small image for each lattice that could superimpose on top of cards.

In any case, this is low priority and does not block the graphic refresh.

**Comment by lordmcfuzz** [comment]
Potentially, all we have to to do is just add another div in between our current top level card div and and everything else with a lattice background with the same pattern of offsets. the lattice would be the lattice over a transparent background.

**Comment by ultimatefiend** [comment]
what if the same lattice were applied to every card?  We could pick one of the fancier ones so there is at least some filler in the black lines that are currently there.

Cities will require a different pattern for the lattice when the time comes.

**Comment by micahstairs** [comment]
This becomes obsolete with the ultimate changes.
