### ISSUE TITLE
Legend doesn't score a card if no effect is executed

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1162]
I had a demand effect as a top card and after executing it, it didn't score and continue the effect.

I'm not sure how the postexecution stuff works otherwise I'd try to fix it myself.

**Comment by micahstairs** [comment]
Oh that's because if you self-execute something and the card only has a demand effect, then there's nothing to execute so post-execution never happens. I guess we need to add a special case.

**Comment by ultimatefiend** [comment]
Legend does a number of weird things (i.e. asking for a new color during every iteration when the color should be the same).

Also, is the scoring that the card refers to only from the scoring of the top cards?  The self-execution can also lead to scoring which could shorten the duration of Legend if those scored cards are counted.

https://boardgamearena.com/bug?id=92452

**Comment by micahstairs** [comment]
I think "scored fewer than nine points due to Legend" means it only refers to cards directly scored via Legend.
