### ISSUE TITLE
Wire through new "draw keyword"

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1173]
This adds support for https://boardgamearena.com/bug?id=92874 and will also help us build the right card transfer messages.

**Comment by ultimatefiend** [comment]
This also helps with cards like Fermi Paradox which don't actually draw cards, but just reveal them.

**Comment by micahstairs** [comment]
Oh nice, that's a good call!

**Comment by micahstairs** [comment]
This will also fix https://boardgamearena.com/bug?id=92775.
