### ISSUE TITLE
Card.php and Innovation.js need some renaming help

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1194]
The innovationkahlia's needed to be added manually:

abstract class Card
{

  protected \innovationkahlia $game;
  protected ExecutionState $state;
  protected Notifications $notifications;

  function __construct(\innovationkahlia $game, ExecutionState $state)
  {

innovation.js needs an Innovation in the bolded spot:

BgaGame = /** @class */ (function () {
    function BgaGame() { }
    return BgaGame;
})();
var Innovation = /** @class */ (function (_super) {
    __extends(Innovation, _super);
    function **Innovation**() { <-- here

**Comment by micahstairs** [comment]
Are you using the rename script on the main-4 branch? We are using it for innovationalpha deployments and it's working fine right now!

**Comment by ultimatefiend** [comment]
This is the command that I use:

c:/dev_area/php/php C:/DEV_AREA/bga/innovationdev/bga-sharedcode/misc/bgaprojectrename.php innovation innovationkahlia

**Comment by micahstairs** [comment]
I wonder if the rename script works differently on windows vs mac.

**Comment by micahstairs** [comment]
Oh wait, you're using the bga-sharedcode script! We don't want to use that one.

Please use the one in our own repo's misc directory (on the main-4 branch).
