### ISSUE TITLE
Implement age 1 echo cards

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1201]
The following only require wording changes:
- [x] Soap
- [x] Umbrella

The following require wording and functional changes:
- [x] Bangle
- [x] Candles
- [x] Plumbing
- [x] Chopsticks
- [x] Noodles
- [x] Comb
- [x] Ice Skates
- [x] Dice
- [x] Perfume
- [x] Ruler
- [x] Bell
- [x] Flute
- [x] Puppet

**Comment by ultimatefiend** [comment]
oh my
