### ISSUE TITLE
Junk deck cards don't have a position

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1204]
I think this is the issue with safe deposit.  If you junk a deck with fermenting (for example), the cards don't appear in the junk browser which suggests that the junk deck operation isn't doing something right.

I see that the code doesn't try to update the order of the cards when it transfers them via the SQL command:

    function junkBaseDeck($age) {
        self::DbQuery(self::format("
            UPDATE
                card
            SET
                location = 'junk',
                position = NULL
            WHERE
                owner = 0
                AND location = 'deck'
                AND age = {age}
                AND type = 0
        ", ["age" => $age]));
        if (self::DbAffectedRow() > 0) {
            self::recordThatChangeOccurred();
            self::notifyAll('junkedBaseDeck', clienttranslate('All cards in the ${age} deck were junked.'),  array('age' => self::getAgeSquareWithType($age, self::BASE), 'age_to_junk' => $age));
        } else {
            self::notifyGeneralInfo(clienttranslate('No cards were left in the ${age} deck to junk.'),  array('age' => self::getAgeSquareWithType($age, self::BASE)));
        }
        
    }

https://boardgamearena.com/bug?id=93387

I suspect if the junked cards show up in the browser (via the junkbasecards function) then safe deposit will work properly.

For reference this is the error you get:
Unexpected error: Error while processing SQL request (Localhost via UNIX socket): UPDATE card SET position = position - 1 WHERE owner = 0 AND location = 'junk' AND type = 0 AND age = 2 AND is_relic = 0 AND position > You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7 (reference: GS1 16/07 05:16:55)

**Comment by ultimatefiend** [comment]
this would also be fixed as well :

https://boardgamearena.com/bug?id=93163

**Comment by micahstairs** [comment]
Oh nice find!! Yeah that definitely seems like the right conclusion.

**Comment by ultimatefiend** [comment]
I think this fixes this as well:

https://boardgamearena.com/bug?id=92476
