### ISSUE TITLE
Transferring to safe from deck should not reveal the card in the log

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1214]
I don't know where to suppress this message, but it should be a secret.

Also, any transfer from an opponent or achievement to the safe should also remain a secret (e.g. Mafia).

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=92775

**Comment by micahstairs** [comment]
This will be fixed when we add the draw_keyword in https://github.com/micahstairs/bga-innovation/issues/1173.
