### ISSUE TITLE
Candles is doing something weird

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1218]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/473a6405-d78a-4ed2-93f1-c8083565febf)

I don't know why a card transfer is happening.

**Comment by micahstairs** [comment]
Oh the text in the materials file was just messed up.

**Comment by ultimatefiend** [comment]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/7c593f5a-cf5d-46f7-8040-10d69662ec80)
