### ISSUE TITLE
Surveillance still doesn't work

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1230]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/6637a741-2254-462c-aa96-eea965d20dd2)

There is a red that doesn't match.

**Comment by ultimatefiend** [comment]
The intersect needs to be done in both directions I think.

  private function isUnorderedEqual(array $a, array $b): bool
  {
    return count(array_intersect($a, $b)) === count($a);
  }

**Comment by ultimatefiend** [comment]
Could also use the array_unique php function instead.

**Comment by ultimatefiend** [comment]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/164134a8-2747-4d04-9370-5cd34dcd5ed2)

**Comment by micahstairs** [comment]
I'm pretty sure we fixed this for once and for all.
