### ISSUE TITLE
Destiny isn't working correctly

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1237]
It seems that this logic isn't working right because you get destiny when 0 cards are in your forecast:

            case 436: // Destiny: A total of 5 cards in forecast (7 in earlier editions)
                $eligible = self::countCardsInLocation($player_id, 'forecast') >= $this->innovationGameState->usingFourthEditionRules() ? 5 : 7;
                break;

![image](https://github.com/micahstairs/bga-innovation/assets/11416698/492c9c60-a49a-4bbe-9cd6-3e6b32548a46)

**Comment by ultimatefiend** [comment]
I suspect that operator precedence might be a problem.

**Comment by micahstairs** [comment]
Good suspicion!

**Comment by ultimatefiend** [comment]
it works now!
