### ISSUE TITLE
Chopsticks echo effect returns an error

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1241]
Server syntax error:
Notice: Undefined index: message_for_player in /var/tournoi/release/games/innovation/999999-9999/innovation.game.php on line 9662

Notice: Undefined index: message_for_others in /var/tournoi/release/games/innovation/999999-9999/innovation.game.php on line 9663

Notice: Undefined variable: options in /var/tournoi/release/games/innovation/999999-9999/innovation.game.php on line 10138
{"status":1,"data":{"valid":1,"data":null}}

**Comment by ultimatefiend** [comment]
from the opponent's perspective:

![image](https://github.com/micahstairs/bga-innovation/assets/11416698/ddc656f7-753b-4f87-805c-df3868085193)

**Comment by micahstairs** [comment]
I suspect this is now obsolete.
