### ISSUE TITLE
Ice skates doesn't draw to hand if forecast is full

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1243]
The 3 destined for the forecast should go to hand if the forecast is full.

**Comment by ultimatefiend** [comment]
Other cards (like Linguistics and Horseshoes) need to check this as well.

**Comment by ultimatefiend** [comment]
chaturanga is affected by this as well (first effect)

**Comment by ultimatefiend** [comment]
Perhaps the drawandforecast function should do this automatically?

**Comment by micahstairs** [comment]
I actually just handled it in drawAndForecast and drawAndSafeguard. I'll close this but please re-open if you see issues.
