### ISSUE TITLE
Toothbrush Echo effect doesn't limit choices based on what is in hand

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1244]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/ecaa5087-de2a-4644-b56d-4c8a1982f248)

**Comment by micahstairs** [comment]
I don't think this is Toothbrush specific. I'm seeing some bug reports about this in the alpha.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=94534
