### ISSUE TITLE
Pagoda returns an error if forecast is full

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1245]
Server syntax error:
Notice: Trying to access array offset on value of type null in /var/tournoi/release/games/innovation/999999-9999/modules/Innovation/Cards/Echoes/Card353.php on line 22

Fatal error: Uncaught TypeError: Argument 1 passed to Innovation\Cards\Card::setAuxiliaryValue() must be of the type int, null given, called in /var/tournoi/release/games/innovation/999999-9999/modules/Innovation/Cards/Echoes/Card353.php on line 22 and defined in /var/tournoi/release/games/innovation/999999-

**Comment by ultimatefiend** [comment]
Also you reveal your hand even if you pass the first optional action (tucking).

**Comment by micahstairs** [comment]
Good find. My fix will fix some general safe/forecast edge cases.
