### ISSUE TITLE
Echoes has priority over Unseen when drawing the first card of a turn in 4th edition

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1246]
Per Micah's comment in Discord

**Comment by ultimatefiend** [comment]
Does this affect the first turn as well?  (the first two cards)

**Comment by micahstairs** [comment]
Echoes already has priority over Unseen, so nothing to fix there. But I'll push a fix for the initial hand. I checked and you're supposed to be start with an Unseen and Echoes if playing with both those expansions.
