### ISSUE TITLE
Ninja claimed the wrong player chose a color

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1250]
I suspect that this is related to notification for the demander getting confused with the person being demanded in the transfer logic.

**Comment by micahstairs** [comment]
Link to bug: https://boardgamearena.com/bug?id=93980

**Comment by ultimatefiend** [comment]
This is confirmed.

**Comment by ultimatefiend** [comment]
It looks like the names are reversed for the color selection. (the opposing players show the wrong player making the choice.)

**Comment by ultimatefiend** [comment]
It might be related to the effect being a demand effect and the demander is making the choice and not the main player

**Comment by ultimatefiend** [comment]
Yes, this is incorrect:

  public function handleSpecialChoice(int $color): void
  {
    $this->notifications->notifyColorChoice($color, self::getPlayerId());
    self::setAuxiliaryValue($color);
  }
