### ISSUE TITLE
Safe Deposit returns an error when transferring the last card from junk to score pile

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1255]
I used canal building to junk the 3s and the last 3 wasn't transferred.

Javascript error:
Script error.
Script:
Url: https://studio.boardgamearena.com/1/innovationkahlia?table=496928
BGA version 230725-1001
U=2359382
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by ultimatefiend** [comment]
If you refresh the page, then the junk browser doesn't show the last card and the last 3 is in the score pile.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=94269

**Comment by micahstairs** [comment]
Closing this bug since it's very old and likely obsolete.
