### ISSUE TITLE
Telescope Age 4 Echo Card366 throws an exception when choosing the achievement to exchange

### ISSUE THREAD

**Issue by Iain27** [micahstairs/bga-innovation#1267]
To reproduce, 4 and 5 in forecast, return 4 , 5 goes to available achievements (no choice on which goes where) When clicking an achievement an exception is thrown

	Server syntax error: 
Warning: array_key_exists() expects parameter 2 to be array, int given in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1414

Notice: Trying to access array offset on value of type int in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1415

Notice: Trying to access array offset on value of type int in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1415

Warning: array_key_exists() expects parameter 2 to be array, int given in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1419

Notice: Trying to access array offset on value of type int in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1420
{"status":"0","error":"Error while processing SQL request (Localhost via UNIX socket): SELECT * FROM card WHERE id = \nYou have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 (reference: GS1 05\/08 06:20:17)","expected":0,"code":500,"stack":"#0 \/var\/tournoi\/release\/tournoi-230725-1001-gs\/www\/include\/APP_DbObject.inc.php(650): APP_DbObject::DbQuery()\n#1 \/var\/tournoi\/release\/tournoi-230725-1001-gs\/www\/include\/APP_DbObject.inc.php(675): APP_DbObject->getObjectFromDB()\n#2 \/var\/tournoi\/release\/games\/innovationdev\/999999-9999\/innovationdev.game.php(4025): APP_DbObject->getNonEmptyObjectFromDB()\n#3 \/var\/tournoi\/release\/games\/innovationdev\/999999-9999\/innovationdev.game.php(1420): innovationdev->getCardInfo()\n#4 \/var\/tournoi\/release\/games\/innovationdev\/999999-9999\/innovationdev.game.php(1397): innovationdev->transferCardFromTo()\n#5 \/var\/tournoi\/release\/games\/innovationdev\/999999-9999\/modules\/Innovation\/Cards\/Card.php(320): innovationdev->junkCard()\n#6 \/var\/tournoi\/release\/games\/innovationdev\/999999-9999\/modules\/Innovation\/Cards\/Echoes\/Card366.php(70): Innovation\\Cards\\Card->junk()\n#7 \/var\/tournoi\/release\/games\/innovationdev\/999999-9999\/innovationdev.game.php(20911):

**Comment by Iain27** [comment]
note sure why it made me create a new branch how do I link the issue without doing that?

**Comment by micahstairs** [comment]
@Iain27 just reference #1267 in the PR somewhere.
