### ISSUE TITLE
Update Blackmail wording and implementation 

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1280]
Blackmail: I DEMAND you reveal your hand!  Meld a revealed card of my choice!  Reveal your score pile!  Self-execute any revealed card of my choice, replacing 'may' with 'must'!

is the self execute only from the score, or does it also consider the cards revealed from hand?

Carl: The cards from the score pile, the cards in your hand, and the card you just melded from your hand.

**Comment by ultimatefiend** [comment]
Oh my...that makes that card WAY more complicated...

**Comment by micahstairs** [comment]
Yeah Carl might reword it... It's not intuitive.

**Comment by micahstairs** [comment]
Let's hold off on making this change right now.

**Comment by micahstairs** [comment]
Okay it's being reworded to "I DEMAND you reveal your hand!  Meld a revealed card of my choice!  Reveal your score pile!  Self-execute a card revealed due to this effect of my choice, replacing 'may' with 'must'!"
