### ISSUE TITLE
ice cream second effect doesn't achieve a card when eligible

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1295]
I selected  a 6 and there were 6s available, plus I had the age and score...and nothing happened.

**Comment by micahstairs** [comment]
I just tested this and it seems to be working fine!

**Comment by micahstairs** [comment]
Actually, I do see something weird going on. The positions of the cards are messed up in the DB and one of the junked cards is not selected.

<img width="188" alt="Screen Shot 2023-08-23 at 6 49 55 AM" src="https://github.com/micahstairs/bga-innovation/assets/7231485/5b213b14-1f67-49e0-ae4d-8ecccf9b4f88">
