### ISSUE TITLE
Propaganda digs too deep to get the transferred card

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1298]
$stack = self::getCardsKeyedByColor('board')[self::getAuxiliaryValue()];
        if (count($stack) >= 2) {
          self::transferToBoard($stack[count($stack - 2)], self::getLauncherId()); <-- This should probably be -1 and not -2
        }

This is currently holding up a game that I am playing with Pitdood.  There is currently one card in the stack and I think that -2 is causing the issue.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=96685

**Comment by micahstairs** [comment]
Well looks like we are trying to subtract 2 from an array. The indexes are right though!
