### ISSUE TITLE
Magnifying Glass needs to check for returned cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1299]
public function afterInteraction() {
    if (self::isNonDemand() && self::isFirstNonDemand()) {
      self::draw(self::getLastSelectedAge() + 2);
    }
  }

NumChosen() isn't present in this check.

https://boardgamearena.com/bug?id=96323

**Comment by micahstairs** [comment]
Well actually we don't need to check numChosen. We don't get this far if there are not 3 cards of the same value (since there is the word "exactly"). But the problem is that we are executing this logic too early. We have to wait until the second interaction.
