### ISSUE TITLE
Extract 6 square icons from cards

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#13]
We need to extract each of the 6 square icons, and place them in a PNG. 

Here are the source images:
- [ ] [castle_and_crown_source.png](../tree/main/misc/square_icons/castle_and_crown_source.png)
- [ ] [factory_and_clock_source.png](../tree/main/misc/square_icons/factory_and_clock_source.png)
- [ ] [leaf_and_lightbulb_source.png](../tree/main/misc/square_icons/leaf_and_lightbulb_source.png)

Please place each in a separate image (naming it something like `castle.png`). Make sure not to resize the image or lower its quality in any way.

Please make sure all icons are the exact same size.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by jacksonmead** [comment]
@micahstairs It looks like factory_and_clock_source.png and leaf_and_lightbulb_source.png are 404.

**Comment by micahstairs** [comment]
@jacksonmead sorry about that, fixed the links!
