### ISSUE TITLE
Liquid Fire with a full forecast leaves cards revealed

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1302]
They are just stuck there.

https://boardgamearena.com/2/innovationalpha?table=411349469

**Comment by ultimatefiend** [comment]
they should be transferred to the demandee's hand in this case since they can't be transferred to the demander's forecast (I think)

**Comment by ultimatefiend** [comment]
This is still happening as of 9/10/2023

https://boardgamearena.com/2/innovationalpha?table=415246005

**Comment by ultimatefiend** [comment]
I think the difference with this card is that the demandee should get the cards and not the demander.

**Comment by ultimatefiend** [comment]
I guess the full forecast logic could look at where the cards are and then use that to determine where they should go

**Comment by ultimatefiend** [comment]
since it is in the demandee's reveal in this case.

**Comment by ultimatefiend** [comment]
This is assuming that's how the full forecast logic "should" work in this case...maybe a question for Carl/Chris.  The demander probably shouldn't end up with the worse end of the deal.

**Comment by micahstairs** [comment]
Liquid Fire says `I DEMAND you draw a card of value equal to the highest bonus on your board! Transfer it to my forecast! If it is red, transfer all cards from your hand to my score pile!`

If the transfer to the forecast fails, the demandee gets to keep the card. There's not a bug here as far as I can tell.

**Comment by micahstairs** [comment]
Missed an above comment. Apparently it's still happening.

**Comment by micahstairs** [comment]
Fixed.
