### ISSUE TITLE
Investigate Card583 failure

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1306]
https://github.com/micahstairs/bga-innovation/actions/runs/5992990744/job/16252979819

**Comment by ultimatefiend** [comment]
Is there a way to recreate the error?

**Comment by micahstairs** [comment]
The error gives the stack trace so it should be easy enough to tell what's wrong by comparing that to the code.

**Comment by ultimatefiend** [comment]
I took a look and I don't know what's going on.  maybe the count function is returning null?  I don't know how that would be a string.

**Comment by ultimatefiend** [comment]
or maybe it returns a single value and that is a string and not an array?

**Comment by micahstairs** [comment]
Oh yeah that's weird, I have no idea. I'll just close this! I will look into it further if it happens again.

**Comment by ultimatefiend** [comment]
Is it possible to create a script from the test that would reproduce the condition in the studio?  (e.g. create a game)

**Comment by micahstairs** [comment]
Hmm that seems really complicated. Not sure that's going to be worth the effort.
