### ISSUE TITLE
Antibiotics returns an error when returning cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1308]
Unexpected error: setStat: Unknown player id: 0 (reference: GS2 29/08 03:53:23)

**Comment by ultimatefiend** [comment]
I reproduced this in studio as well.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=96982

**Comment by micahstairs** [comment]
Yeah I do have a fix in innovationdev for this.
