### ISSUE TITLE
Barometer doesn't look at other boards in first effect

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1315]
Effect says to consider bonuses on any board:

      $bonuses = self::getBonuses();
      if (self::isFirstOrThirdEdition()) {
        foreach (self::getOtherPlayerIds() as $playerId) {
          $bonuses = array_merge($bonuses, self::getBonuses($playerId));
        }
      }
      if ($bonuses) {

The bonuses for other boards are only used in first and third editions.

**Comment by micahstairs** [comment]
Fixes https://boardgamearena.com/bug?id=97212.
