### ISSUE TITLE
Bandage isn't working properly

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1317]
I think the issue is here:

  public function handleCardChoice(array $card) {
    if (self::isFourthEdition() && self::isDemand()) {
      if (self::isFirstInteraction()) {
        self::setAuxiliaryValue(1);
      } else if (self::getAuxiliaryValue() === 1) {
        self::setMaxSteps(3);
      }
    }
  }

This isn't tracking how many cards were chosen, thus stating that the effect was successful.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=97262

**Comment by ultimatefiend** [comment]
that code should also check if the affected player has any achievements before setting the max steps to 3.

**Comment by micahstairs** [comment]
I don't think we need to check if the affected player has any achievements before setting the max steps to 3. If they have no achievements then the interaction will automatically just get aborted since n=0.

**Comment by micahstairs** [comment]
Also I don't think that's the bug. We only call handleCardChoice when there was a card that was picked.

**Comment by micahstairs** [comment]
I suspect this may have already been fixed.
