### ISSUE TITLE
Space Traffic stops too early in 3+ player games

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1321]
// "If you do not have the highest score, repeat this dogma effect."
                    $highest_score = false;
                    $player_score = self::getPlayerScore($player_id);
                    foreach (self::getAllActivePlayerIds() as $player) {
                        if ($player_score > self::getPlayerScore($player))  {
                            $highest_score = true;
                        }
                    }

This doesn't check the absolute highest score only whether one player has a lower score.  It needs to first figure out the highest score and then determine if the current player has the highest score.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/bug?id=95451

**Comment by micahstairs** [comment]
Oh nice find! Yeah I'll fix this.
