### ISSUE TITLE
Seed Drill's second effect is not clear and doesn't work right

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1323]
Choose the 3, 4, or 5 deck. You may junk all cards in the chosen deck. If you do, achieve the highest junked card if eligible.

I thought you would achieve the highest card that was junked in the second sentence.  Instead, the maximum age of the cards in the junk pile is achieved instead.

Also, if you don't junk anything you still get the achievement.

**Comment by ultimatefiend** [comment]
This needs to be conditional on whether the pile was junked or not:

    } else {
      self::junkBaseDeck(self::getAuxiliaryValue2());
      self::setMaxSteps(3); <-- this line
    }

**Comment by micahstairs** [comment]
I think the card is clear. There wouldn't be any reason to use the term "highest" if it was referring to a deck that was just jumped, since they'd all be the same value.

I agree with the assessment on the bug though.

**Comment by ultimatefiend** [comment]
I think its unclear.  FWIW, NickJim had the same interpretation I did.  Usually the cards are more specific about which cards its talking about...like the cards that resulted from the effect or the global state of the game.  The effect, as worded, does not distinguish between these two.

**Comment by micahstairs** [comment]
Ah that's a good point (thinking about how this compares to the situation where cards refer to `melded card`). I raised this question to Chris and Carl.
