### ISSUE TITLE
Junk all cards before eliminating a player

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1324]
"You lose" implicitly implies that all cards should be junked.

**Comment by ultimatefiend** [comment]
They should be excluded from glory and victory achievements though I think.

**Comment by micahstairs** [comment]
I checked and it if just says "You lose", then yes, you can't get the achievement since your achievement zone no longer exists. Exxon Valdez says `I COMPEL you to junk all your cards! You lose!`, so in this case you could grab an achievement and win right before you were about to lose.

**Comment by micahstairs** [comment]
I fixed this last week.
