### ISSUE TITLE
Attic needs "score_keyword"

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1329]
} else {
      return [
        'location_from' => 'hand',
        'location_to'   => self::getAuxiliaryValue() == 1 ? 'score' : 'safe', <-- if this is score, then score_keyword needs to be true
      ];
    }
  }

**Comment by micahstairs** [comment]
Were you looking at the wrong branch?

The main-4 code is already as followed:
```
$keyword = self::getAuxiliaryValue() == 1 ? 'score_keyword' : 'safeguard_keyword';
      return [
        'location_from' => 'hand',
        $keyword        => true,
      ];
```

**Comment by ultimatefiend** [comment]
I was looking at my local branch and looking at the behavior of the current game (which transfers cards in the first effect)

**Comment by micahstairs** [comment]
Oh yeah I fixed this 4 days ago looking at the file history. About to do an alpha push now.
