### ISSUE TITLE
Implement Museum mechanism for 4th edition artifacts

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1342]
https://asmadigames.com/innovation/PatchNotes_Ultimate.pdf

**Comment by ultimatefiend** [comment]
> Display: At the start of the turn after you dig an Artifact and put it On Display, you may choose to take a free
> Dogma action targeting it. Whether or not you did, it then rotates into a Museum (placed face-up on top of it).
> There are five Museum cards, and when all five are in use, the player with the most Museums claims one as an
> Achievement, and then returns all Artifacts in Museums and returns the rest of the Museums to the supply.
> 
> Museums: You may meld an artifact in a museum with a Meld action. You may target an opponent’s artifact
> in a museum with a Dig event.

It looks like you can't choose to return an artifact.  It will end up in a museum no matter what you do.  The rules don't state what happens when no museums are left.  What happens to the artifact in this case, is it returned?

As discussed in chat, you get the museum and the artifact when you steal it via the dig event.

I think in the event of a tie, the artifacts and the museums are still returned.

It doesn't say anything about melding from the display.  Is that still a feature or can you only meld from a museum?

**Comment by micahstairs** [comment]
For completeness, here are the rules as specified by Carl on May 24th;

At the start of the game, place the five Museum cards to the side of the ages.  Like Decrees from the Figures expansion, Museums are not "special achievements", but may be claimed as achievements during the game if certain conditions are met.
During a dig event, a player places an artifact from the appropriate age in their display.  If there is already an artifact in their display, the dig event is ignored.  An artifact in the display cannot be melded (unlike in 3rd edition) or dogmad.
At the beginning of a player's turn, before their First and Second Actions, a player with an artifact in their display may take a free Dogma action with that artifact, counting the artifact's icons in addition to their board icons when determining share eligibility.  (Cards fully executed from other zones due to card effects do not add their icons to the board total in this way.)
Whether the player takes the free Dogma action or not, the player then rotates the artifact into an available Museum, playing the Museum in front of them behind their other board cards, with the artifact card on top in a crosshatch pattern.
If there are no available Museums, the player rotates the artifact into their hand instead.

If a player rotates their artifact into the last available Museum, the player immediately returns all artifacts in all Museums in front of all players, and the Museums are rotated back to availability.  If there was a single player with the most Museums in front of them, that player claims one  of the (identical) Museum cards as an achievement.
During a player's turn, a player may use a Meld action to meld an artifact from a Museum in front of them onto their board.  If they do, they rotate the Museum card back to availability.  A player may make two such Meld actions to meld two artifacts from their Musuems during the same turn if desired.
During a dig event of a given value, normally a player gains an artifact of that value, taking from a higher age if the base card deck of that value is depleted.  A dig event is not a draw.  (These are true in 3rd edition also.)
However, if during a dig event of a given value an opponent has an artifact of that same value in their Museum, the player may decide to forego the artifact from the decks and instead rotate the opponent's Museum along with the artifact in it to in front of the player.  The value of the rotated artifact must match exactly, even if the base deck of that value is empty. 
A rotate is not a transfer, and does not trigger Figures looking for a transfer.

**Comment by micahstairs** [comment]
Here's a list of things that still need to be implemented:
- [x] An artifact in the display cannot be melded
- [x] The artifact needs to be rotated into a museum after passing
- [x] The artifact needs to be rotated into a museum after dogma-ing it
- [x] If there are no available Museums, the player rotates the artifact into their hand instead.
- [x] Artifacts can be melded from the player's museums
- [x] Make the museum available again if an artifact was melded from a museum
- [x] Players can steal an artifact/museum from another player if the value matches
- [x] If a player rotates their artifact into the last available Museum, the player immediately returns all artifacts in all Museums in front of all players, and the Museums are rotated back to availability. If there was a single player with the most Museums in front of them, that player claims one of the (identical) Museum cards as an achievement.
