### ISSUE TITLE
Bar Code 2nd effect doesn't offer a choice of splay when not foreseen

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1354]
This is missing a path for adding a step for selecting a splay:

    if (self::isFirstOrThirdEdition()) {
      self::setMaxSteps(1);
    } else {
      if (self::isDemand()) {
        self::setActionScopedAuxiliaryArray(self::getBonuses()); // Track values left to remove from score pile
      } else if (self::wasForeseen()) {
        for ($color = 0; $color < 5; $color++) {
          self::splayUp($color);
        }
      }
    }

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/table?table=420347320

**Comment by micahstairs** [comment]
I'm going to split Flash Drive and Barcode into different files. The effects changed a lot between editions and there's no value in trying to stuff things into the same file.
