### ISSUE TITLE
bifocals didn't draw a card equal to the lowest available achievement

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1364]
There were about 15 available and it drew a 1 instead.

**Comment by ultimatefiend** [comment]
https://boardgamearena.com/2/innovationalpha?table=422185801

**Comment by micahstairs** [comment]
Oh I updated the implementation but forgot to update the actual text of the card. It should say "Draw and foreshadow a [7].  If Bifocals was foreseen, draw and foreshadow a card of value equal to the lowest available standard achievement."

**Comment by ultimatefiend** [comment]
ahh

**Comment by ultimatefiend** [comment]
1 definitely wasn't available so that probably isn't working right either.

**Comment by micahstairs** [comment]
Oh this was caused by the AVAILABLE_ACHIEVEMENTS bug. The card behavior will get updated next time I refresh the card list (so we don't need a bug tracking this now).
