### ISSUE TITLE
Lever returns an error when selecting values to draw

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1367]
It says "server error".

**Comment by ultimatefiend** [comment]
This is blocking this table:

https://boardgamearena.com/2/innovationalpha?table=422797354

**Comment by ultimatefiend** [comment]
This appears to work in studio so maybe this isn't a problem anymore?

**Comment by micahstairs** [comment]
Oh I fixed this in https://github.com/micahstairs/bga-innovation/commit/fff045fde455655643aa4b3f5a1ef11a27197fbf last week!
