### ISSUE TITLE
Artificial heart didn't claim an eligible achievement

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1368]
I had 23 points and an 8 was available, but it didn't transfer.

https://boardgamearena.com/2/innovationalpha?table=423119408

**Comment by ultimatefiend** [comment]
Actually this is probably the same issue as bifocals.

**Comment by micahstairs** [comment]
Okay then I'll close this since the underlying issue is fixed in main-4.
