### ISSUE TITLE
Bar Code is still broken

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1375]
It returns an error when executing it non-foreseen.

**Comment by micahstairs** [comment]
What kind of error?

**Comment by ultimatefiend** [comment]
It said server error so not very specific.

**Comment by ultimatefiend** [comment]
if (self::isFirstOrThirdEdition()) {
      self::setMaxSteps(1);
    } else {
      if (self::isDemand()) {
        self::setActionScopedAuxiliaryArray(self::getBonuses()); // Track values left to remove from score pile
      } else if (self::wasForeseen()) {
        foreach (Colors::ALL as $color) {
          self::splayUp($color);
        }
      }
    }

The demand doesn't set the max steps to 1.  The second part looks problematic as well since you can have the same bonus more than once which would lead to more than one of that value being returned:

        $values = self::getActionScopedAuxiliaryArray();
        $cardIds = [];
        foreach (self::getCards('score') as $card) {
          if (in_array($card['age'], $values)) {
            $cardIds[] = $card['id'];
          }
        }
        self::setAuxiliaryArray($cardIds);
        return [
          'location_from'                   => 'score',
          'return_keyword'                  => true,
          'card_ids_are_in_auxiliary_array' => true,
        ];

This is the text from the card:

I DEMAND you return a card of matching value from your score pile for each bonus on your board!

I think that means that if you have two bonus 7s and two 7s in score pile both 7s would be returned.

**Comment by ultimatefiend** [comment]
It probably needs to be in a loop where you can count down the number of values like with Lever.
