### ISSUE TITLE
Create an "on display" area

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#138]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

The rules for artifacts calls for an "on display" area where artifacts are placed after they are dug up (via a dig event).  This area needs to be accessible to the user and allow them to perform the two optional events at the beginning of their turn (neither counts as an action):

1)  Perform a free dogma action of the on display artifact.  The symbols on the card are added to the current counts for the purposes of executing this dogma.
2)  Return the on display artifact to the pile it was drawn from (thus allowing another artifact to be drawn).

After that initial part of the turn, the on display artifact can only be melded onto the board with a meld action (just like melding from hand).

**Comment by ultimatefiend** [comment]
I had a couple of thoughts on this:

1.  Making a separate box (like the "hand" box) on the screen on the far right might be the simplest way to display it.  This would be visible to all players and could only contain one artifact card.  At the beginning of the turn, the engine would highlight the card and add the additional symbols to the display on the far right to show that the symbol count is enhanced.  It would also show the three options for the artifact:  Dogma, return, or pass.
2. If someone wants to meld the artifact, they can just click on the card just like they do the cards in hand during the normal course of their turn.
3. If the artifact expansion isn't being used, then this box would not appear.

The separate box makes the card on display more obvious and easier to interact with rather than putting it on the reference card.

**Comment by micahstairs** [comment]
I agree that a separate "on display" box makes sense. The reference card isn't large enough to put a card on it and I don't think it would look good to make it bigger, especially on mobile.

**Comment by micahstairs** [comment]
I'll start with the first part of this: getting the new area in the UI, and making it possible to transfer cards to and from the zone.

**Comment by ultimatefiend** [comment]
This isn't quite working right.  Dogma and Return actually counts as an action during the turn.  At least in the rev I've been working from.

**Comment by micahstairs** [comment]
> This isn't quite working right. Dogma and Return actually counts as an action during the turn. At least in the rev I've been working from.

I don't think this is happening in any version of the code I'm working with.

So to update this issue, the work left here is to improve the layout of the Artifact zone (right now it's way larger than necessary), and also to include the resource icons of the artifact when executing it from the display (a difficult PHP change, and some easy CSS/Javascript changes).

**Comment by micahstairs** [comment]
I think I'll close this issue since it might be a while before I get around to adjusting the Artifact zone placement. The goal of this issue (creating a functional "on display" area) is complete.
