### ISSUE TITLE
X-Ray doesn't allow you to foreshadow "any number of them" per the text on the card

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1392]
I think the root is here:

        return [
          'n'                               => self::getAuxiliaryValue(),
          'location_from'                   => Locations::HAND,
          'foreshadow_keyword'              => true,
          'card_ids_are_in_auxiliary_array' => true,
        ];

It should be n of "1" and not the aux value and it should repeat until they pass.

**Comment by micahstairs** [comment]
Let's do this instead:

```
'can_pass'                      => true,
 'n_min'                           => 1,
'n_max'                           => self::getAuxiliaryValue(),
```

**Comment by ultimatefiend** [comment]
I tested this and it works.
