### ISSUE TITLE
Rotating more than one artifact from museums results in the artifacts on top of each other

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1403]
Also, the museum itself (the black card) appears to disappear?

**Comment by micahstairs** [comment]
Do you have a screenshot? Not quite sure what you are referring to here. Are you referring to when you are returning artifacts from the museums?

**Comment by ultimatefiend** [comment]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/3ecdb7a0-c2b4-4422-a21c-e5dac614fc08)

There are two museums there.

**Comment by ultimatefiend** [comment]
I set it up so that I could steal two museums (by melding my own 1 museums) and this was the result.

**Comment by ultimatefiend** [comment]
I'm referring to rotating the museum from your opponent to  your own museums.

**Comment by ultimatefiend** [comment]
after a page refresh:

![image](https://github.com/micahstairs/bga-innovation/assets/11416698/488763a1-36e0-4041-a90f-a81b29ba46b3)

**Comment by micahstairs** [comment]
I can't replicate it. I think I fixed it.
