### ISSUE TITLE
Only 1 age 11 artifact appears in the card browser

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1412]
One of them is missing as well (the stack size is only 9).

**Comment by ultimatefiend** [comment]
Age 11 artifacts also don't appear in the card selection drop down list in the studio

**Comment by micahstairs** [comment]
I intentionally deferred the implementation of "Martian Internet":

> Start a new game, each player drawing a [9] to begin, without shuffling any cards, ignoring all players' current cards. The winner of that game transfers their cards to this game. Junk each player's cards from that game.
