### ISSUE TITLE
Psyche returns an error

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1413]
Server syntax error:
Notice: Undefined offset: 1 in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1449

Notice: Undefined offset: 2 in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1449

Notice: Undefined offset: 3 in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1449

Notice: Undefined offset: 4 in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1449

Notice: Undefined offset: 5 in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 1449

**Comment by micahstairs** [comment]
This is already tracked by https://github.com/micahstairs/bga-innovation/issues/1400 (it was detected by my integration tests a while ago).
