### ISSUE TITLE
Ark of the Covenant isn't working the way it says on the card

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1429]
"Return a card from your hand. Score all cards of the same color on the boards of all players with no top Artifacts."

Just dogma's this card and it returned my yellow cards despite the fact I had two artifacts as top cards.  It did not score cards from my opponent who did not have any artifacts.

Also, it put ark in my hand which is a third edition behavior.

**Comment by ultimatefiend** [comment]
if (!$hasTopArtifact) {
        foreach (array_reverse(self::getStack($color)) as $card) {
          if (self::isFirstOrThirdEdition()) {
            self::transferToScorePile($card);
          } else {
            self::score($card);
          }
        }
      }

This logic isn't specifying the specific player to get the card from.

**Comment by ultimatefiend** [comment]
and this should check the edition:

  public function afterInteraction()
  {
    if ($card = $this->game->getIfTopCardOnBoard(CardIds::ARK_OF_THE_COVENANT)) {
      self::transferToHand($card);
    }
  }

**Comment by ultimatefiend** [comment]
Did this get pushed?  It still isn't working right as the cards are going to the wrong score pile.

**Comment by micahstairs** [comment]
Other people seem to be reporting the same issue here: https://boardgamearena.com/bug?id=103187.
