### ISSUE TITLE
Add a way to select from a list of values

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#143]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Currently, you can select from a list of age values (1-10) using "choose_value" but you can't select a subset of the ages.

This is needed for East India Company Charter.

**Comment by micahstairs** [comment]
When using `'choose_value' => true`, you can now use `'age' => array(1, 2, 3, 8, 9)` to control which values the user can pick.

**Comment by ultimatefiend** [comment]
Nice!  Thanks.
