### ISSUE TITLE
Loom didn't lead to heritage with 5 icons in the second effect

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1432]
![image](https://github.com/micahstairs/bga-innovation/assets/11416698/f64da6fb-baa6-44c4-a01a-03dab0eb2f3b)

Purple had 5 icons and I wasn't rewarded the achievement (and it was available).

**Comment by ultimatefiend** [comment]
This looks ok depending on what Colors::All gives you:

   } else {
      foreach (Colors::ALL as $color) {
        if ($this->game->countVisibleIconsInPile(self::getPlayerId(), Icons::HEX_IMAGE, $color) >= 5) {
          $this->game->claimSpecialAchievement(self::getPlayerId(), CardIds::HERITAGE);
          break;
        }
      }

Purple is the last color so maybe that has something to do with it?

**Comment by micahstairs** [comment]
You must be looking at the wrong branch. This is what's there:

```
foreach (Colors::ALL as $color) {
        if (self::getIconCountInStack($color, Icons::HEX_IMAGE) >= 5) {
          self::claim(CardIds::HERITAGE);
          break;
        }
      }
```

Oh I see the problem though, that works on all icons except for the hex icons.
