### ISSUE TITLE
Communist Manifesto doesn't meld a card to the opponents board

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1433]
All cards drawn are melded to the player executing the dogma instead of giving a card to each player.

**Comment by ultimatefiend** [comment]
The auto execution definitely works at the end.  The other cards aren't transferred though.

**Comment by ultimatefiend** [comment]
Player id isn't using the selected value:

 public function getInteractionOptions(): array
  {
    if (self::isFirstInteraction()) {
      return [
        'choose_player' => true,
        'players'       => self::getAuxiliaryArray(),
      ];
    } else {
      return [
need player id selection here
        'location_from' => Locations::REVEALED,
        'location_to'   => Locations::BOARD,
      ];
    }
  }

**Comment by micahstairs** [comment]
Just pushed a fix (also tracked in https://boardgamearena.com/bug?id=103934).
