### ISSUE TITLE
Special Achievement counters aren't correct for some achievements

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1443]
Monument (# demands) is not counting the right thing.

The unseen specials don't seem to make sense.  What does 1/2 mean?

![image](https://github.com/micahstairs/bga-innovation/assets/11416698/a11289f9-f15e-493a-a621-c451e1b3c60c)

**Comment by micahstairs** [comment]
Zen is looking for two things:
- You have a top card on your board of value 6 or higher
- No top card on your board is of odd value

Can you tell what Monument is counting? The implementation looks right to me.

**Comment by ultimatefiend** [comment]
I can't tell.  I only had 2 top demands.  My opponent had 1.

**Comment by ultimatefiend** [comment]
it might make more sense to highlight what is satisfied and what is not satisfied for the unseen achievements

**Comment by micahstairs** [comment]
Fixed the bug with Monument! I agree that's a good idea, but it's not worth the effort right now.
