### ISSUE TITLE
Add a filterable "choose_player" option

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#149]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

The options array doesn't allow you to select a specific opponent to target with a dogma (when the turn order and the dogma order effect isn't specified).

It would also be great if we could filter the effect so it would only target players that would be eligible for an interaction.

**Comment by micahstairs** [comment]
Which cards will we need this for other than "The Communist Manifesto"?

Regarding, "It would also be great if we could filter the effect so it would only target players that would be eligible for an interaction", I think it will be up to the implementation of each card to determine which target players are eligible.

**Comment by ultimatefiend** [comment]
Yes, that is what I meant.  It would be filterable via a secondary parameter like the "color" for choose_color or "age" for choose_value.

**Comment by ultimatefiend** [comment]
this might be needed for Charter of Liberties depending on how we do it.

**Comment by micahstairs** [comment]
I don't think we will need this for "Charter of Liberties". I'd prefer to let the player directly click on the pile instead of having a 2-step process.

But yeah, I'll make this filterable via a secondary parameter.
