### ISSUE TITLE
Seikilos Epitash isn't working properly

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#151]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

The "meld from bottom" behavior is not working properly.

First, when the card is melded to the top, you can't select it unless you refresh your browser.
Second, the sharing card is not correct.  The old top card is the age used for the sharing card.

So, I think transferring from board->board is acting strangely when the board is the same.

I saw some weird behavior when I tried this before and there is a second card that has similar behavior (Moonlight Sonata) so I wanted to check how it was done.

**Comment by micahstairs** [comment]
Thanks for catching this! Your suspicions sound right to me. I'll need to take a closer look at this later, but I think we could use a special location (sorta like "revealed,hand" to handle this).

**Comment by ultimatefiend** [comment]
I think revealing the card first would be acceptable and probably easier than trying to fix the board->board transition.  There isn't a board->revealed transition yet (there is another issue for that).

**Comment by micahstairs** [comment]
I completely agree. One thing we'd have to do is after revealing and before transferring it back to the board, we'd need to refetch the card info. I'd we re-use the first variable variable then the card will have some out of date information which will cause problems with the transfer

**Comment by ultimatefiend** [comment]
This doesn't work for the "maintain splay" case.  It is also unclear if moonlight sonata should maintain its splay if the bottom card is melded on top and there are only two cards in the splay.

**Comment by micahstairs** [comment]
To maintain the splay, we could check the splay direction beforehand and then resplay after. I suppose this might lead to a few extra notifications telling everyone that the pile was unsplayed and then resplayed. Do we care about that?

Also, since Moonlight doesn't say to maintain its splay, I suppose it loses its splay?
