### ISSUE TITLE
Update summary and strategy tips sections in the BGA wiki

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#156]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Need to add new Artifact rules summary and we have been talking about adding a card FAQ to the strategy tips tab.

Some ideas:
Puffing Billy (a card needs to be returned to activate the second part of the dogma)
Pride and Prejudice (no splay case)

Need an explanation/example of #100 as it can be confusing and different from the base set.

**Comment by micahstairs** [comment]
I'd recommend drafting this in a Google Doc. Then we can quickly copy it over to the wiki when it's actually time to release the expansion.

**Comment by micahstairs** [comment]
I started a Google doc: https://docs.google.com/document/d/1-FnA2Al_VvS-3_8sb0zJWQ8m4aGxYU9iHlLpfqeiCak/edit.

Please make changes via suggestions, or ask me for edit access.

**Comment by micahstairs** [comment]
In the documentation, we need to make sure we mention the rule change about special achievement timing (https://boardgamearena.com/bug?id=62821) since the latest rulebook is now out of date.

**Comment by ultimatefiend** [comment]
I took a stab at the documentation.  Let me know what you think.

**Comment by micahstairs** [comment]
@ultimatefiend I don't see your changes in https://docs.google.com/document/d/1-FnA2Al_VvS-3_8sb0zJWQ8m4aGxYU9iHlLpfqeiCak/edit. Did you put it in a different doc?

**Comment by ultimatefiend** [comment]
Sigh.  My changes appear to be lost.  I'm not sure what happened.

**Comment by ultimatefiend** [comment]
Micah, I think I'm satisfied with the new content.  let me know if you need anything else.

**Comment by ultimatefiend** [comment]
Is it possible to put it on the alpha page for people to read and give feedback?

**Comment by micahstairs** [comment]
I just went through your draft of the summary, made some changes and added it to the alpha:

<img width="1477" alt="Screen Shot 2022-07-01 at 12 50 19 PM" src="https://user-images.githubusercontent.com/7231485/176937311-1610ef92-6400-4b2c-aa6d-8e69a594c227.png">

I haven't gone through the strategy tips yet.

**Comment by micahstairs** [comment]
I just did the same for strategy tips. I think we are ready to close this!
