### ISSUE TITLE
Add score->revealed transition

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#166]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Twister needs to reveal cards from a score pile.  That doesn't appear to be implemented yet.

**Comment by micahstairs** [comment]
Just a note about the in-progress Twister implementation: you're currently trying to use an interaction to make the player reveal all of the cards from the score pile. You should instead do the transfer automatically.
