### ISSUE TITLE
Extract number images from bonus icons

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#172]
Building on top of the work we started in #134, we now want to extract smaller circles from each bonus icon which only contain the numbers 1 to 11. Let's put these in a spritesheet with these numbers side by side.

The reason for this is that rather than having images for each of the 11 numbers multiplied by 5 different colors, we are going to 5 have just 5 images with the colored borders and then superimpose the number images on top of it in-game.

This task must be done using ImageMagick. You can add this to circle_icons.sh.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by ultimatefiend** [comment]
Out of curiosity, what are your thoughts on displaying the numbers on the tableau?  Isotropic displays the largest (and full value) bonus icon in bold coloring and then has a greyed out appearance for each symbol beyond that (the ones that are worth 1 point).  That seems like a straightforward way of conveying that information.

Perhaps we can save this discussion for when we have to show these icons somewhere, but it might be relevant for image creation.

**Comment by micahstairs** [comment]
The greyed out icons sound like an interesting idea for making it easier for players to interpret their board, but the simplest solution is just to include the bonuses in the score total in the player panel. So I'm not sure there's any real need to add this extra feature.

**Comment by ultimatefiend** [comment]
icon window being the player board area where the number of icons are shown.  The number of hex icons in a particular pile will also be useful for heritage

**Comment by ultimatefiend** [comment]
I think the point is the distribution of point icons is pivotal in many of the cards.  Having that be really obvious would help people play their cards better.

I guess with the boards actually having the points visible would be beneficial generally speaking.  isotropic doesn't have that so they had to make due.
