### ISSUE TITLE
Seized relics are not subtracted from the player score at the end of the game

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#191]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

If a relic is stolen from another person, the BGA score is not correct at the end of the game.  It doesn't get removed from their player score for some reason.

**Comment by micahstairs** [comment]
Have you confirmed whether this is a frontend-only bug or is the database also not reflecting the proper number of achievements (BGA player score)?

**Comment by ultimatefiend** [comment]
I think this is a bug in the back end implementation on my end.  I should be able to test a fix tonight after kiddo bedtime.
