### ISSUE TITLE
Fix bug in bgaprojectrename.php script

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#192]
Part of our development flow relies on the bgaprojectrename.php script in https://github.com/elaskavaia/bga-sharedcode.

For example, if your BGA project is named InnovationJohnSmith, you would run a command like:

```
php bga-sharedcode/misc/bgaprojectrename.php innovation innovationjohnsmith
```

Unfortunately, there is a bug in the script which causes the innovationjohnsmith.action.php file to contain `class action_innovationjohnsmithjohnsmith extends APP_GameAction` instead of `class action_innovationjohnsmith extends APP_GameAction`. If the name of the action class is wrong, then when you start a game you will just see a blank white screen.

This bug also affects other BGA developers which use the same script, so fixing this will also make their lives better too!

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by lordmcfuzz** [comment]
line 55 of the php script needs a space in the regex so it looks like `$content= preg_replace( "/action_${oldprojectname} /", "action_${newprojectname} ", $content);`

**Comment by lordmcfuzz** [comment]
I'll make a PR for them

**Comment by lordmcfuzz** [comment]
PR can be found at https://github.com/elaskavaia/bga-sharedcode/pull/3

**Comment by micahstairs** [comment]
Thanks for the fix! I'll close this.
