### ISSUE TITLE
Update game progression formula for Artifacts expansion

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#200]
In innovation.game.php there is a `getGameProgression` function which is used to show players the estimated completion of the game:
<img width="164" alt="Screen Shot 2022-01-23 at 9 35 11 PM" src="https://user-images.githubusercontent.com/7231485/150712855-aac47123-ed52-4e48-8905-795c8752a99f.png">

We need to revise this formula now that we are adding an expansion. We need to make sure the progression formulas work for all cases:
- Base game
- Artifacts without relics
- Artifacts with relics
- With or without an extra achievement to win (new game option we are adding)

If you want to work on this, it might be worth getting a discussion going on our Discord and get input from others on the formulas we should use.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by ultimatefiend** [comment]
I don't think this needs to change.  It is already considering how many achievements are needed to win which is set based on the expansions added and the extra option.

**Comment by ultimatefiend** [comment]
Also, drawing out the artifacts doesn't cause the game end sooner like the base cards.

The game might take longer because people are bewildered by the artifacts...heheh.

**Comment by ultimatefiend** [comment]
On second thought, the "Free Action" will occur a number of times during the game which would create more interactions and thus cause the game to be longer.

**Comment by micahstairs** [comment]
Even if the game takes longer because of Artifacts, I don't think that needs to affect the percentage completion. I think you're right that we don't need to update it.
