### ISSUE TITLE
Mobility is broken

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#208]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

                // id 78, age 8: Mobility        
                case "78D1A":
                    if ($n > 0) {
                        $color = self::getGameStateValue('color_last_selected');
                        $selectable_colors = self::getAuxiliaryValueAsArray();
                        $selectable_colors = array_diff($selectable_colors, array($color)); // Remove the color of the card the player has chosen: he could not choose the same for his next card
                        self::setGameStateValueFromArray($selectable_colors);
                    }
                    break;

setGameStateValueFromArray has two arguments.

**Comment by ultimatefiend** [comment]
I don't see any other places where the argument is missing.

**Comment by micahstairs** [comment]
Nice find! setGameStateValueFromArray just needs to be updated to setAuxiliaryValueFromArray.

**Comment by micahstairs** [comment]
Fixed in https://github.com/micahstairs/bga-innovation/commit/3f1cb160fb23071dd9c3bff749f47c12fa9d25d2.
