### ISSUE TITLE
Review all cards that may be affected by an eliminated player

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#212]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

With the introduction of Exxon Valdez, all cards in both the base and artifacts needs to be tested/improved to deal with a removed player.

  - [x] **Chronicles of Zuo**
  - [x] **Communist Manifesto**
  - [x] **Dancing Girl**
  - [x] **Clothing**
  - [x] **Optics**
  - [x] **Construction**
  - [x] **Bioengineering**
  - [x] **Globalization**
  - [x] **A.I.**
  - [x] **Maastricht** (No effect as the eliminated player can't have any cards on their board)
  - [x] **Road Building** (choices are reduced)
  - [x] **seikan**
  - [x] **specialization** (no board = no cards to transfer)
  - [x]  **East India Company Charter** (can't return cards from an eliminated players score pile)
  - [x] **Ark of the Covenant**
  - [x] **Mask of Warka**

**Comment by ultimatefiend** [comment]
I think (generally speaking) any card that has to query for all players will need to query for active players instead.  It might be as simple as looking for loadPlayersBasicInfo() and doing a replace and then test it.

**Comment by micahstairs** [comment]
Dancing Girl is a bit of an exception though, since it uses a counter to see if it's traveled to every board. And the expected end value of the counter will change depending on the number of players.

**Comment by ultimatefiend** [comment]
Dancing Girl already takes into account active players so we should be good.
