### ISSUE TITLE
Fix Seikan

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#215]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

There is a clarifying statement on Seikan Tunnel so this can be resolved:

                    // TODO: Revise wording once we get a clarification on https://boardgamegeek.com/thread/1937834/seikan-tunnel-artifact-rules-question.

**Comment by micahstairs** [comment]
I'll take this. Right now this card is making a lot of SQL queries, so I'm going to write a custom query so that we can optimize this.
