### ISSUE TITLE
When no 10 artifacts remain, there is an offset to the card layout

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#224]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

https://cdn.discordapp.com/attachments/901924170890358845/939014852188442665/unknown.png

While testing Rover, I encountered this:

![image](https://user-images.githubusercontent.com/11416698/152615770-b1193162-4f54-4a48-82e0-08e48a0c77a5.png)

**Comment by micahstairs** [comment]
Thanks for finding this bug! There should be a simple CSS fix here.

**Comment by lordmcfuzz** [comment]
Reproduction steps:

Run out the artifact 1/5/6/10 deck and see the deck set shift. If you return the the last card to the empty pile the deck will shift back into position. After the deck set is shifted and refresh of the page will fix visual bug.
