### ISSUE TITLE
Add support for looking at the top card of a deck

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#227]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Piano (Echoes) and The Daily Courant (Artifacts) need the ability to look at the top card of a deck.  Would it be sufficient to print it to the log or should the card be drawn and returned to the top of the deck?

We don't have support in the "transfer" API to do that at the moment.  When a card is returned to the deck, it is always put on the bottom.

**Comment by micahstairs** [comment]
Based on the wording on the card, I think it would be best if we actually drew the card and put it back on top. I'll take a look at how easy it will be to make this change to the API.

**Comment by micahstairs** [comment]
Okay I added support for this:

```
self::transferCardFromTo($card, 0, 'deck', /*bottom_to=*/ false);
```

And the log will say something like: "You topdeck X from your hand"

I checked the database to confirm that the card is going to the correct location.
