### ISSUE TITLE
Give players option to choose 11 when it makes sense

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#231]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

With the introduction of Battleship Yamato, there will be cases where players should be given the option to choose the value 11 (normally only 1-10 are options).

Chris only wants us to show 11 as an option when it's absolutely necessary. For example, with PLUSH BEWEGLICH ROD BEAR, it says to choose a value and splay up each color with a top card of the chosen value. If Battleship Yamato is a top card on that player's board, then 11 should be an option, but if Battleship Yamato is not a top card, then only 10 should be an option.

We need to take a look through the cards and see if there are others which need similar treatment.

**Comment by ultimatefiend** [comment]
Chemistry is one that comes to mind.

**Comment by ultimatefiend** [comment]
but there is no choosing I guess.

**Comment by ultimatefiend** [comment]
I think PLUSH is the only one that has a "choose_value" where you choose based on the top card's value.  Mass Media, East India, and Metre Bar also have choices but you can't choose outside the age range.

**Comment by micahstairs** [comment]
I think you're right. Plush seems to be the only card in the Base/Artifacts that this affects.

I just looked at the implementation and I think this will be a quick fix. This is blocked on Battleship Yamato actually being added though.
