### ISSUE TITLE
Add an option to get all top cards on all boards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#235]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Delorean needs the ability to select all top cards (and not the cards below them) on all boards so they can be removed from the game.

However, this option doesn't exist.  If there were something limiting the depth of the selection (so the second and subsequent cards cannot be selected), then this would fit the bill.

**Comment by ultimatefiend** [comment]
Charter of Liberties could benefit from this if the starting selections were configurable.

**Comment by ultimatefiend** [comment]
Here is some code to start from for delorean:

(213, 1,10, 4, 0, 6, 6, 6, 6),

            // id 213, Artifacts age 10: DeLorean DMC-12
            case "213N1":
                // "If DeLorean DMC-12 is a top card on any board"
                $player_ids = self::getAllActivePlayerIds();
                foreach($player_ids as $player_id) {
                    if(self::isTopBoardCard($player_id, 213)) {
                        $step_max = 1; // go to the removal stage
                    }
                }
                break;

**Comment by micahstairs** [comment]
So for these two cards, we basically want something where we can indicate whether or not a pile can be selected. Each player can have 5 piles, so this is 20 bits of information. We will want to add an option called `piles` which takes an integer representing a bitset. We will need to establish an ordering for which part of the bitset each player's piles represent. I propose we use `player_no` which goes from 1...N where N is the number of players. This will make it easy enough to shift the bits to the right locations.

**Comment by ultimatefiend** [comment]
I agree with that approach.  That sounds great.  If you can pair it with "location= none" then this can have very generic uses (like with Fission).

**Comment by ultimatefiend** [comment]
if they are removed all at once, we will need a way to determine tie breakers for special achievements.

**Comment by ultimatefiend** [comment]
Gujin (age 5) would also benefit from this feature too.  So, all of the remaining cards would be unblocked by this feature.

**Comment by micahstairs** [comment]
In other cases when we have to break a tie (consider the case where a card is transferred from the board of one player to another player's board), the priority goes in turn order, beginning with the player who's turn it is.

But hmm, okay, I will take a look at the remaining cards and think about whether using 20 bits to represent the 20 piles is the simplest solution :)

**Comment by micahstairs** [comment]
I don't think we need this complicated 20-bit solution. I see cleaner solutions to address Charter of Liberties and Gujin Tushu Jinsheng, so I'll close this.
