### ISSUE TITLE
Prevent Battleship Yamato from being activated

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#239]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Battleship Yamato does not have a featured icon and therefore is not allowed to be the target of a dogma action. I've already stopped it from being an option when a player is using one of their actions, however, nothing is stopping it from being chosen during nested execution via a card like Self Service.

Let's start by putting together a list of all of the affected cards and then figure out the best way to address this. It's likely that using `'not_id' => 188` will be a good solution, but we need to add a `not_id_2` option if the affected cards are already using `not_id`.

**Comment by ultimatefiend** [comment]
daily courant

**Comment by micahstairs** [comment]
We will also need to consider cards like Satellites which says "Meld a card from your hand and then execute each of its non-demand dogma effects. Do not share them." The player should be allowed to choose Battleship Yamato, but we should gracefully handle the case where there is no dogma effect.

**Comment by ultimatefiend** [comment]
Satellites can't meld an artifact since you have to return all cards before melding.

**Comment by micahstairs** [comment]
Oh true! Maybe "Priest-King" is a better example ("Score a card from your hand. If you have a top card matching its color, execute each of the top card\'s non-demand dogma effects. Do not share them.").

**Comment by micahstairs** [comment]
Actually, I don't think it's a problem if a player chooses Battleship Yamato during nested execution. I think that should be the correct interpretation of the rules.

Confirmed we are handling this correctly:
<img width="245" alt="Screen Shot 2022-03-27 at 9 42 51 PM" src="https://user-images.githubusercontent.com/7231485/160312541-6f057d3e-548b-4900-b216-0a7c3cf7da6c.png">
