### ISSUE TITLE
Fix layout of .M cards with small font and in-line icons

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#245]
Take a look at Oars:

<img width="202" alt="Screen Shot 2022-02-13 at 8 31 57 PM" src="https://user-images.githubusercontent.com/7231485/153785625-2afb22b7-1dfb-4540-9291-5f76132ec9e0.png">

I think we can make some improvements to how icons are rendered within dogma text, especially when the font is on the smaller side.

**Comment by lordmcfuzz** [comment]
The big challenge here is that we currently have a fixed icon size in text, while our text is magically dynamic.

**Comment by lordmcfuzz** [comment]
So I can "scale" the icon(age and symbol) but I don't think it improves much, aka it does not increase text size:
![image](https://user-images.githubusercontent.com/4430835/163732687-497c9534-feef-4538-a333-15bc267cce78.png)
@micahstairs  thoughts?

**Comment by lordmcfuzz** [comment]
I published a branch called INNO-245 incase you want to try it out.

I do admit I did not confirm that we were picking the font size with the scaled items in account. I should double check.

**Comment by lordmcfuzz** [comment]
This is using 'middle':
![image](https://user-images.githubusercontent.com/4430835/163737700-1077213d-4e93-480a-82a8-2c9e45a5be35.png)

**Comment by micahstairs** [comment]
This is in a much better state now: <img width="191" alt="Screen Shot 2022-06-11 at 7 49 28 PM" src="https://user-images.githubusercontent.com/7231485/173208507-d94d8e1b-1765-43ab-b0ef-920da3247ec3.png">
