### ISSUE TITLE
Melding an artifact leaves a white box

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#249]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

After clicking on the artifact to meld, this white box remains:

![image](https://user-images.githubusercontent.com/11416698/154336726-874d4b37-9a01-4c34-9a19-54e6745bc2c2.png)

**Comment by lordmcfuzz** [comment]
Dev note: bug is due to the div(display-{player-id} style height being set to 0.
