### ISSUE TITLE
Make spritesheet of card backgrounds in portrait mode

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#25]
We need a spritesheet which contains the 11 cards which are in portrait orientation (all 10 age cards from https://github.com/micahstairs/bga-innovation/tree/main/misc/card_backgrounds, and also https://github.com/micahstairs/bga-innovation/blob/main/misc/card_backgrounds/special_achievement_portrait.png), with 5 pixels of whitespace around each image.

From left to right, the icons should be: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, Special Achievement

You **must** use ImageMagick for this task since we will be regenerating these images later on with a variation of the command you build. You can heavily base your command off of https://github.com/micahstairs/bga-innovation/blob/main/misc/imagemagick_commands/background_spritesheet.txt. This task should be very quick to do! If I had easy access to ImageMagick, I'd quickly do it myself.

Place the resulting image in
https://github.com/micahstairs/bga-innovation/tree/main/misc/square_icons. And place the command in https://github.com/micahstairs/bga-innovation/tree/main/misc/imagemagick_commands.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by normaljosh** [comment]
Done, but it looks like special_achievement_portrait.png might not actually be in portrait mode

**Comment by micahstairs** [comment]
Thanks for flagging that issue. I've updated the image, can you regenerate the spritesheet?
