### ISSUE TITLE
Unable to select achievement to claim

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#253]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

While testing Complex Numbers, I discovered it wasn't possible for me to select an achievement to claim. Not sure if this is a backend bug or a frontend bug. Also not sure if this is just a bug in my Complex Numbers implementation or if this affects other cards too. This requires more investigation.

<img width="689" alt="Screen Shot 2022-02-17 at 10 16 27 PM" src="https://user-images.githubusercontent.com/7231485/154611315-de55b003-52d9-4317-8c9d-8114b67e1429.png">
<img width="198" alt="Screen Shot 2022-02-17 at 10 16 34 PM" src="https://user-images.githubusercontent.com/7231485/154611318-b0f94616-b2cc-46a1-ac25-a8e6a65ad291.png">

**Comment by ultimatefiend** [comment]
This used to work.  Some other cards let you do this.

**Comment by micahstairs** [comment]
Yes, I remember this working for other cards too!

**Comment by micahstairs** [comment]
Just confirmed that the achievement card is being selected in the database.

<img width="1434" alt="Screen Shot 2022-02-18 at 9 51 53 AM" src="https://user-images.githubusercontent.com/7231485/154705851-c2d65969-200d-41f0-93f5-bc1de51cb969.png">

**Comment by micahstairs** [comment]
Fixed it!
