### ISSUE TITLE
Make Rosetta Stone reveal cards instead of putting them in hand

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#257]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Instead of drawing two cards to hand, I think it would be better if the drawn cards went to the revealed area, since the two cards are going to end up as top cards on the board (so the information doesn't need to be private).

**Comment by ultimatefiend** [comment]
is this needed?  I'd rather not mess with anything unless its necessary.

**Comment by micahstairs** [comment]
I classified it as an enhancement because I believe it will make the user experience a bit better. It gives opponents the chance to read the cards while the player is deciding who to give them to.

Feel free to unassign yourself if you aren't interested in this and I will tackle it later.

If you think this will make the user experience worse for whatever reason, please let me know!

**Comment by ultimatefiend** [comment]
If the card doesn't say to reveal it, should we?  I'm not sure.

I understand what you are saying about giving the opponent more time to view the cards that were drawn though.

**Comment by micahstairs** [comment]
Hmm that's a fair point. Maybe we shouldn't change this after all.
