### ISSUE TITLE
Stop prompting player to make decision about seizing relic if it can't be moved

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#259]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

This bug happens when the relic cannot be seized to hand (because the relic is not from Base or Artifacts) and it's already in the player's achievement pile.

![seize-bug](https://user-images.githubusercontent.com/7231485/154824254-4f847d23-134b-4702-afec-7f87a943f17f.png)

**Comment by ultimatefiend** [comment]
hmm... that's interesting.  That only happened before because the 'age' was specified in the function for detecting seizing instead of the 'type'.
