### ISSUE TITLE
Resource counts get out of sync when meld happens during free action

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#262]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Steps to reproduce: have 0 crowns before free action of artifact on display -> perform Lurgan Canoe to meld Domestication -> icon count changes from 3 to -2

![dogma-and-return](https://user-images.githubusercontent.com/7231485/154847530-23026ae0-1652-4458-b8a7-61b72bb1d6d2.png)

I know *why* this is happening but I will need to think a bit about the best way to fix it.

**Comment by micahstairs** [comment]
I think I have a solution for this. Right now we are updating the artifact on display icons by applying a delta value to the current counters. I think it would be better if the backend sent absolute values instead of relative values.

This is a fairly substantial change but I think it is a more straight-forward solution and will fix this bug in the process.

**Comment by lordmcfuzz** [comment]
absolute over relative. As one not familiar with how it works, A compromise solution may be just grab absolute after the end of the free action.

**Comment by aia-e** [comment]
This also happens with Tale of the Shipwrecked Sailor

**Comment by micahstairs** [comment]
This bug will affect any melds that happen while executing the free dogma action

**Comment by micahstairs** [comment]
Actually I found a simple fix. I made a change to unhighlight the featured icon as soon as the player chooses what to do with their Artifact on display.
