### ISSUE TITLE
Boerhavve Silver Microscope doesn't correctly calculate the value of the card that needs to be scored

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#265]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

According to Aiae, Boerhavve Silver Microscope doesn't correctly calculate the value of the card that needs to be scored (seems to be the card returned from board -1).

![play-2](https://user-images.githubusercontent.com/7231485/154871285-10f5c177-b7d5-4722-a0ea-b13e53e2bd8f.png)

![unknown](https://user-images.githubusercontent.com/7231485/154871313-4996c017-45b4-4881-a21b-63edb528d319.png)

**Comment by ultimatefiend** [comment]
I reproduced this and I agree with the conclusion.  It looks like the faceup_age might not be right maybe?  I'm certain this worked before.

**Comment by micahstairs** [comment]
Aiae is still reporting this.
