### ISSUE TITLE
Cards are incorrectly topdecking instead of returning to the bottom of the deck

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#266]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

When adding support for topdecking I accidentally introduced a bug which breaks other cards (e.g. Tools).

**Comment by ultimatefiend** [comment]
all returns are top decking at the moment.
