### ISSUE TITLE
Improve how nested card execution is communicated in the game log

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#272]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

I'm marking this as a bug instead of an enhancement because right now it has the hard-coded text "execute the effects of X as if it were on Y", and we need to use card names instead of X/Y.

![nested-2](https://user-images.githubusercontent.com/7231485/154984222-5663f1a0-f2ac-45f7-887e-ff3a501fb447.png)

![nested](https://user-images.githubusercontent.com/7231485/154984228-5836cde1-82bf-4252-99ce-8be29e95abf7.png)

**Comment by ultimatefiend** [comment]
Also, the new icon should be mentioned since the new card text inherits the dogma icon.

**Comment by micahstairs** [comment]
Made some progress:
<img width="247" alt="Screen Shot 2022-02-28 at 10 09 56 PM" src="https://user-images.githubusercontent.com/7231485/156097707-785dc1f0-c20e-4bbc-919b-53542dc806aa.png">

I still want to improve the logging for specific effects on the card instead of "You have to execute the 1st non-demand effect".
