### ISSUE TITLE
Change when special achievements checks happen

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#274]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

From Chris (in conversation with Carl):

> For special achievements, we had a long discussion and what we'd like to move forward with is that checks for special achievements happen at the end of any effect (or action).
> 
> So, at the end of any player's execution of any (dogma/echo/inspire)effect, check for Empire, Universe, etc, but not between clauses/sentences of an effect. This is a small change, but it's cleaner going forward. This means that when a group of cards is returned together, you can just cleanly put them in a "to be returned zone" or some such for the player to return one-by-one.
> 
> If an effect is executed because of the text of another effect, checks for special achievements would happen at the end of each sub-effect.

**Comment by lordmcfuzz** [comment]
That was quick

**Comment by micahstairs** [comment]
Haha yeah. I wanted to get this change in early so that we had more time to playtest it.
