### ISSUE TITLE
Fix bug in Holy Grail

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#277]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

There is a bug in the second interaction because we are making the assumption that a card was returned from hand. We should only advance to the second interaction if a card was returned (otherwise we'd treat the absence of a card as 0 and there is no achievement of matching value). If we don't fix this, then age_last_selected could be stale from an opponent playing this card first.

**Comment by ultimatefiend** [comment]
done.
