### ISSUE TITLE
Automate card transfers in Battleship Bismarck

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#280]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

"Return all cards of the drawn color from your board" shouldn't be an interaction.

**Comment by ultimatefiend** [comment]
This has to be an interaction.  We can't automate this.

**Comment by ultimatefiend** [comment]
Return order must be determined by the player.

**Comment by micahstairs** [comment]
Ah good point!
