### ISSUE TITLE
Fix bug in Xianrendong Shards

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#281]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

There's currently a bug here where some of the card_id_X variables could be holding stale card IDs from when an opponent executed the card. We should initialize these at the start of 121N1.

**Comment by ultimatefiend** [comment]
This seems to work as well.  card_id_X must be initialized between dogma effects?

**Comment by micahstairs** [comment]
card_id_x is initialized between dogmas but not between players executing that same dogma. Do you see how this introduces a subtle bug here? We should make sure we re-initalize the variable at the start of 121N1.

Note: even if it ends up being impossible for this bug to have an impact on the game, it's much easier to reason about the correctness of the code if we can guarantee ourselves that the value is not stale.

**Comment by ultimatefiend** [comment]
I see.  I will add the init then.
