### ISSUE TITLE
Fix bug in Baghdad Battery

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#283]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

There are bugs in the implementation because we are making an assumption that cards were melded. When that assumption is broken, id_last_selected could be stale.

**Comment by ultimatefiend** [comment]
if cards aren't melded the card isn't supposed to do anything.  Did you find a problem during testing?

**Comment by ultimatefiend** [comment]
The card seems to work fine, FWIW.

**Comment by micahstairs** [comment]
As we chatted about over Discord, I just want to make sure there's 0% chance we are relying on a stale value, even if we can't seem to trigger the bug when playtesting.

**Comment by micahstairs** [comment]
Turns out we don't need to guard this code with "$n > 0" in this particular function.
