### ISSUE TITLE
Fix Petition of Right

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#285]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

We get a weird log message when n = 0. I think we should only advance to the interaction when $number > 0.

![unknown (2)](https://user-images.githubusercontent.com/7231485/155181932-8742ca7f-85e8-4d23-ab93-bcca124730fe.png)

Also, we can reduce the number of strings to translate by using "card(s)" instead of "card' and "cards".

**Comment by ultimatefiend** [comment]
I got this one.
