### ISSUE TITLE
Highlighting of the active dogma is not working

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#308]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

In the past, the current dogma text would be highlighted while it was performed.  This appears to not be working now.

**Comment by micahstairs** [comment]
Nic catch! I know this was working a few months ago, but I hadn't noticed it stopped working. I expect this will be an easy fix.

**Comment by micahstairs** [comment]
I suspect that this broke when I add the type and is_relic to the card's IDs. This should be a simple fix in `getJSCardId()`.
