### ISSUE TITLE
Returning from hand leads to top decking

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#309]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

This seems to be the default behavior now which is incorrect.

Shroud of Turin was where I first noticed it, but it is happening elsewhere as well.

**Comment by ultimatefiend** [comment]
I think a special "top decking from hand" function could be implemented and that would satisfy the need for daily courant (and the purple echoes card that does this too) without jeopardizing the basic functionality.

**Comment by micahstairs** [comment]
Actually I already add a topdeck option. I think there's just a minor bug in the implementation. This should be very easy to fix.
