### ISSUE TITLE
Revealing cards causes a Javascript error

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#311]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Alchemy causes this to happen.  Some other cards as well.

**Comment by micahstairs** [comment]
I'm not able to reproduce https://github.com/micahstairs/bga-innovation/issues/311. Can you reproduce after force refreshing?

**Comment by micahstairs** [comment]
I'm closing this because I think this was just caused by a stale version of the Javascript.
