### ISSUE TITLE
When returning artifacts, they are being top decked and not put on the bottom

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#315]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

we kept getting the same artifact over and over in a game.

**Comment by micahstairs** [comment]
So I can reproduce the issue you are describing, but I think the returning behavior is actually working correctly. It seems that the cards are being dug from the right side of the deck. And I think this is being reflected backwards in the UI.

Deeper investigation is required.
