### ISSUE TITLE
Satellites doesn't verify a card was melded before trying to auto-execute

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#318]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

This is a reported bug on BGA.

Basically, the logic makes the assumption that a card was melded:

                case "90N3A":
                    $card = self::getCardInfo(self::getGameStateValue('id_last_selected')); // The card the player melded from his hand
                    self::executeNonDemandEffects($card); // "Execute each of its non-demand dogma effects"
                    break;

It doesn't verify that one was melded with the last dogma step.  Socialism can take the 8s in hand before the originator has a chance to go.  In that case, satellites should not do anything in that last step.

**Comment by ultimatefiend** [comment]
a simple if ($n > 0) would do the trick to fix this behavior.

**Comment by micahstairs** [comment]
This was deployed a few weeks ago.
