### ISSUE TITLE
After 6 achievements, new achievements wrap to a second row when there visible space available.

### ISSUE THREAD

**Issue by lordmcfuzz** [micahstairs/bga-innovation#321]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.
![image](https://user-images.githubusercontent.com/4430835/158500705-927de1e2-9904-4064-a42c-13479f9b9b1f.png)

*make it work better*

Notes: the positions are absolute in the box, the div has no width, and for some reason each one as an ascending z-index
might have to do with:
![image](https://user-images.githubusercontent.com/4430835/158500805-483c9dc0-c8fa-46a7-b880-ff13b90473bf.png)

**Comment by micahstairs** [comment]
The ascending z-indexes correspond with each card's position within a location. This really only matters for location like the deck or the board, where cards are stacked on top of each other instead of side by side.

**Comment by micahstairs** [comment]
![Screenshot_20220319-081002](https://user-images.githubusercontent.com/7231485/159120578-183e216e-3900-4f28-846c-4dbadb21a4ed.png)

I just noticed that on mobile we are allocating way too much space for achievements and not enough for score cards. So maybe we need to configure the calculations different on mobile?
