### ISSUE TITLE
After returning a relic, it should be faceup according to the rules

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#324]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

The rules state this:

"If a relic would be returned, place it face-up next to its matching supply pile.  If a relic is in your achievements pile for any reason, it should be face-up, so all players know it is available to be seized."       

Do we want to implement this?  I think the relics that can be returned (i.e. the 4 and 5 at the moment) should be displayed in some way so you know what you are seizing to hand before you seize it to hand.

**Comment by ultimatefiend** [comment]
The second part of that sentence is more alarming because that suggests that the 3,6, and 7 relics should also be shown as well which means we'd have to render them.

**Comment by micahstairs** [comment]
We are definitely not going to render them faceup! Way too much work.

What we could consider doing is making sure players can hover over relics and see what the card is. What do you think about that?

**Comment by ultimatefiend** [comment]
Yeah, I think that would work.  Could we also add a halo when the relic is in the achievement pile to make it more obvious that it can be stolen?

**Comment by micahstairs** [comment]
Tell me more about the halo. Normally this means that the card can be clicked on.

**Comment by ultimatefiend** [comment]
yeah that's true.  Maybe the relics can be sorted towards the end of the achievements?  anything to make it obvious that the relics are different than the other achievements

**Comment by micahstairs** [comment]
I mean... They already have a unique background to make them stand out. Sorting it is possible, but I still think players are going to want to read the dogma effects before seizing the card in their hand.

**Comment by ultimatefiend** [comment]
This is a question for Chris I think.  The spirit of the rule is that you want to make it obvious that a card can be stolen.  How do we do that in our UI?  I think that's the big question.  I agree that the relics are mostly obvious.  They will get less obvious as we move onto the other expansions though.

If he's happy with the way its presented and it is obvious to the general user what can be stolen, then we don't need to do anything.

**Comment by micahstairs** [comment]
Hmm I vaguely remember asking him about this. I'll have to search through my email thread with him and see if I can dig it up. However, I don't know if he'd have a strong opinion on this.

I think we make it obvious enough that it can be stolen (especially since we prompt the user if they want to seize it). 

I personally think the reason it should be faceup is so that players can know what the effect will be (and this can be accomplished with tooltips).

**Comment by ultimatefiend** [comment]
Ah ok.  That is true about notifying them.  The notification is hard to ignore. :)

Also, FWIW the new people I've introduced to the game seem to pick up on the concept and how to get them.

**Comment by micahstairs** [comment]
Okay great! So it sounds like the only action item of this issue is to make sure players can read the proper relics via a tooltip at all times?

**Comment by ultimatefiend** [comment]
Yes, I think that would be really great.  If a tooltip could show up in prompt at the top that would be even better (where it asks whether you want to seize a relic to hand or not)

**Comment by micahstairs** [comment]
This improvement is blocked by #331 (otherwise the frontend won't always have the data it needs in order to render a tooltip).

**Comment by micahstairs** [comment]
<img width="944" alt="Screen Shot 2022-04-16 at 8 16 05 PM" src="https://user-images.githubusercontent.com/7231485/163695080-2f7084a9-d6c1-428f-b227-efd8f0fbf660.png">

**Comment by micahstairs** [comment]
I'm going to close this. I think we've addressed the main pain point.
