### ISSUE TITLE
Tortugas Galleon returns a JS error when more than one value is transferred from the score pile

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#326]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

                    // TODO(ARTIFACTS): Fix front-end bug which occurs when this effect is triggered and more than one card is transfered.

**Comment by micahstairs** [comment]
I was able to replicate the bug

```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Object.i.set (dojo.js:1:53351)
    at Object.e.style (dojo.js:1:70522)
    at Object.addToZone (:8084/data/themereleases/current/games/innovation/999999-9999/innovation.js?1647698426687:2108:18)
    at Object.moveBetweenZones (:8084/data/themereleases/current/games/innovation/999999-9999/innovation.js?1647698426687:2098:22)
    at Object.notif_transferedCard (:8084/data/themereleases/current/games/innovation/999999-9999/innovation.js?1647698426687:3259:18)
    at r.<anonymous> (dojo.js:1:23159)
    at r.a [as ontransferedCard] (dojo.js:1:43047)
    at Function.o.emit (dojo.js:1:39041)
    at Function.o.emit (dojo.js:1:39670)
    at r.emit (dojo.js:1:42648)
```

**Comment by micahstairs** [comment]
Ah so I think the issue is that after we transfer the first card, the position of the remaining cards change, so we are trying to transfer the next card with stale data about its position, which confuses the frontend.

**Comment by micahstairs** [comment]
There's likely quite a few other cards where we made this same mistake. I will need to double check all `foreach` sites.

**Comment by micahstairs** [comment]
This will only affect cards coming from a hidden location (e.g. score or opponent's hand). So it won't affect any cards being moved from the board or revealed area.

**Comment by micahstairs** [comment]
Statistics from the base game shows us how to handle the stale card data properly:

```
// id 51, age 5: Statistics
            case "51D1":
                if (self::getGameStateValue('game_rules') == 1) { // Last edition
                    // Get highest cards in score
                    $ids_of_highest_cards_in_score = self::getIdsOfHighestCardsInLocation($player_id, 'score');

                    // Make the transfers
                    foreach($ids_of_highest_cards_in_score as $id) {
                        $card = self::getCardInfo($id);
                        self::transferCardFromTo($card, $player_id, 'hand'); // "Transfer all the highest cards in your score pile to your hand"
                    }
                }
                else { // First edition
                    $step_max = 1; // --> 1 interaction: see B
                }
                break;
```

**Comment by micahstairs** [comment]
I went through all of the PHP code and left TODOs on the affected cards.

**Comment by ultimatefiend** [comment]
Cards affected by this bug:
Mask of Warka
Tortugas
twister
mona lisa
sync com 3
