### ISSUE TITLE
Games without relics show the relic-specific statistics at the end of the game

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#330]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

![image](https://user-images.githubusercontent.com/11416698/160036020-78ef1831-2050-4ef4-b488-eba288811919.png)

Not sure why this is happening.  The statistics for the relics aren't initialized in game mode == 3 which is supposed to enable relics.

**Comment by micahstairs** [comment]
So it turns out this is not a bug. Apparently uninitialized stats appear for every game. This isn't ideal but it's a BGA-wide problem. I checked with other BGA devs and they said to proceed with adding expansion-specific stats even though they will be uninitialized when the expansion is not in use.
