### ISSUE TITLE
Add a statistic tracking how many artifacts have been dogma'd (while on your board)

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#334]
This is slightly different than the current statistic that tracks when the card was dogma'd and returned.

**Comment by micahstairs** [comment]
A simpler statistic might be counting the number of melds coming from the display?

I worry that if we are counting artifact dogmas that it won't be representative since they can be indirectly executed through cards like Self Service

**Comment by ultimatefiend** [comment]
we have a statistic "Number of dogma actions".  The new one would only report dogma actions of artifacts.

I don't know how that works with the current nested execution cards like satellites.

**Comment by micahstairs** [comment]
Nested execution doesn't count towards that stat because you didn't use a dogma action to directly execute the card.

Would ""Number of dogma actions targeting an artifact on your board" be clear enough?

**Comment by ultimatefiend** [comment]
yeah that sounds good
