### ISSUE TITLE
Make reference card clickable and allow player to flip through reference card images

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#339]
Instead of having a massive tooltip for the reference card, we should make the reference card clickable and show a popup which allows the player to flip through the reference cards one at a time. This design will make it easier to add new reference cards for expansions (the addition will be tracked in a separate issue).

**Comment by micahstairs** [comment]
See https://en.doc.boardgamearena.com/Game_interface_logic:_yourgamename.js#Dialogs,_warning_messages,_confirmation_dialogs,_.

**Comment by micahstairs** [comment]
Not sure whether this is something we should do or not.

**Comment by ultimatefiend** [comment]
We could move it to the echoes/cities milestone if we don't need it.  I agree that it seems optional as long as the wiki has the appropriate content.

**Comment by micahstairs** [comment]
I detached it from the milestones altogether.
