### ISSUE TITLE
Remove text from reference card

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#34]
We need to remove **all** text from https://github.com/micahstairs/bga-innovation/blob/main/misc/reference_cards/side_1.png and https://github.com/micahstairs/bga-innovation/blob/main/misc/reference_cards/side_2.png. For the second image, make sure to leave all of the images on it (as well as any text on the sample cards like Agriculture).

So basically we need to reconstruct the checkerboard background in its place. Do not reconstruct the checkerboard underneath where it says "SCORE" and "ACHIEVEMENTS".

The reason we need to do this is because we have to instead write translated text on the reference card in-game.

You do not need to use ImageMagick for this task, but can instead do whatever is easiest for you. Just make sure you don't have the dimensions/quality/extension in any way.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by jacksonmead** [comment]
@micahstairs Do we care if we have the same dark and light squares repeated across the whole image? Or do we need to try to keep the uniqueness of each square in the checkerboard?

Alternately, any chance we can get the original application files from the publisher, so we could just snag that background by itself?

**Comment by micahstairs** [comment]
@jacksonmead Given that the text is more readable in the top-left (where the background is a bit lighter), how about we use lighter squares across the whole image?
