### ISSUE TITLE
Claiming wonder gives you some error text

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#343]
Server syntax error:
Notice: Undefined index: condition_for_claiming in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 2562

Notice: Undefined index: alternative_condition_for_claiming in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 2563

Notice: Undefined index: condition_for_claiming in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 2596

Notice: Undefined index: alternative_condition_for_claiming in /var/tournoi/release/games/innovationdev/999999-9999/innovationdev.game.php on line 2597
{"status":1,"data":{"valid":1,"data":null}}

**Comment by micahstairs** [comment]
Nice find! This will be an easy fix.
