### ISSUE TITLE
Make it possible to browse the full list of cards in-game

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#345]
There is a current way to view the full list of possible cards via Isotropic, but there is no way to view the full artifact card list.

Some cards (like Holy Lance) needs to know where other cards exist.  It also might be helpful for people to read through the cards that exist.

**Comment by ultimatefiend** [comment]
I've had a few people ask for this due to some of the interconnectivity of the cards.  My one friend takes screen shots every time a new card comes up.

It might not be too hard to render an HTML page with each of the cards since we do that dynamically during the game.  I don't know if we can link such a page to the wiki, but it might be a good mechanism for sharing this info.

**Comment by ultimatefiend** [comment]
I don't know how we'd handle translations.  I imagine we wouldn't as this was never done previously.  They use to reference the old isotropic site which had a printout of the old cards.

**Comment by ultimatefiend** [comment]
It would have to be some sort of dynamic window (like the score window) that has a button on the table somewhere.  It could be a button per expansion to make it easier to dynamically include it as needed.  Whatever it is needs to run through the translator.

**Comment by ultimatefiend** [comment]
This will be more important once Echoes goes out and there are 105 new cards.  Having the cities cards seems less important but might be relevant when checking for when symbols fade out by age since that is different in Cities (e.g. there is a city with castles and a clock in it in age 5).

**Comment by ultimatefiend** [comment]
Cards like "saxophone" have references to other specific cards and it would be nice for users to know in what ages they would appear.

**Comment by micahstairs** [comment]
Okay, adding it as release-blocking seems reasonable, but we will definitely get this out to alpha first.

It will take a bit of work to get this working, but I know it will be well-received.

**Comment by micahstairs** [comment]
I'm imagining a popup which has buttons to select which set you want to view and another set of buttons for selecting the age you want to view. And then we would render those 10-15 cards in the popup.

**Comment by micahstairs** [comment]
A workaround might be to add something to the ID calculation so that the reference cards have completely different IDs.

**Comment by micahstairs** [comment]
Work in progress screenshot: <img width="1007" alt="Screen Shot 2022-12-12 at 3 58 35 AM" src="https://user-images.githubusercontent.com/7231485/207003572-cb846bd3-8009-4971-9698-0c3f0436567f.png">
