### ISSUE TITLE
Add more debug buttons to game

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#35]
Right now, there is a dropdown list that lets you select any card and then a button that says `DRAW THIS CARD`. Let's extend this functionality to make it easier to set up situations for testing. This will be useful for when we are implementing expansions.

I'd like to see 3 buttons added:
- `SCORE THIS CARD`: Takes a card from its deck and places it in your score pile. Fails if the card is not currently in its deck.
- `ACHIEVE THIS CARD`: Takes a card from its deck and places it in your achievement pile. Fails if the card is not currently in its deck.
- `RETURN THIS CARD`: Takes a card from either your hand or score pile and returns it to its deck. Fails if the card is not currently in your hand or score pile.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

In order to develop code for Innovation, you will need to make a clone of the project on BGA Studio. This will give you a separate workspace for testing your changes. It will take a bit to get set up, but once you're set up, it will be easier to make contributions in the future. Here's a rough set of steps to follow:
- Create a developer account at https://studio.boardgamearena.com/.
- Read through https://en.doc.boardgamearena.com/First_steps_with_BGA_Studio.
- Make an empty project on BGA Studio for your workspace. Maybe name it InnovationYourNameHere?
- In the Studio's Control Panel, use `Overwrite YourProjectName with Innovation` to copy the code I currently have pushed to BGA Studio and copy it to your project (which won't always match what's currently in the main branch, but that's okay). We shouldn't have to worry about merge conflicts because I will generally only file tasks which will have fairly isolated changes.
- Copy the code to your machine using SFTP. Personally I like to use VS Code to do this file sync (see https://en.doc.boardgamearena.com/Tools_and_tips_of_BGA_Studio).
- Once you've made and tested your changes, you'll need to create a pull request with your changes (you might need to manually copy some files from wherever your BGA project is stored locally to wherever your git branch lives).
- I will review and test your changes myself before merging.

**Comment by ultimatefiend** [comment]
How about a separate draw button for each expansion?  the drop down list will be unmanageable soon...

**Comment by micahstairs** [comment]
Hmm I'm not sure we want to eventually have 4 separate drop-down boxes. However we may want to consider some sort of search box.

**Comment by ultimatefiend** [comment]
Some sort of filter would be good maybe?  Also, denoting which card belongs to which expansion would be useful as the list expands (there will be 105 * 5 cards in that list when we are done).

**Comment by normaljosh** [comment]
Good ideas, I'll work on adding in a filter and expansion indicator while I work on the return this card logic

**Comment by micahstairs** [comment]
Since I assumed normaljosh wasn't actively working on this I decided to start working on the return and dig buttons as well as improving the look of the debug buttons.

**Comment by normaljosh** [comment]
Yep, I'll probably work on innovation stuff more after the holidays, thanks for taking this on!
