### ISSUE TITLE
Clear TODO in SCSS to convert .Square.P to use mixe-ins

### ISSUE THREAD

**Issue by lordmcfuzz** [micahstairs/bga-innovation#351]
There seems to be an inconsistent background position progression and could not be adapted to the mixin generator. Attempt to correct the inconsistency and have it use the mixin generator.

**Comment by lordmcfuzz** [comment]
@micahstairs Where do we use size P?

**Comment by micahstairs** [comment]
It's used in the player panel, yeah!
