### ISSUE TITLE
Render Bonus Icons on the cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#354]
The bonus icons need to have their own unique value in the database so the proper icon can be dropped on the cards.  The values span from 1-11.

**Comment by micahstairs** [comment]
Yeah I think we were planning on using values 101-111 so that they are easy to convert in our heads when we read code.

**Comment by micahstairs** [comment]
The scope of this issue won't include any database work though, it will be a pure front-end change.

**Comment by micahstairs** [comment]
There's still some tweaking that needs to be done on the exact positioning, but this unblocks work on a lot of Echoes cards. Will mark this as closed and we can revisit it later (as well as rendering on .L cards). None of those are high priority now though.

<img width="1152" alt="Screen Shot 2022-05-14 at 8 40 40 PM" src="https://user-images.githubusercontent.com/7231485/168452625-4afafaef-4825-4eef-983a-3925d0d798fc.png">
