### ISSUE TITLE
Execute Echo effects when a top card is dogma'd

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#359]
If a top card is executed, the visible echo effects are executed starting from the bottom and working up to the top.  The echo effects on the top card are executed before executing the dogma effects of the card. The echo effects are shared as well (if the top dogma is shared).

This applies to nested execution as well.

Artifact cards on display also execute the echo effects in their colored pile when dogma'd while in the display.

**Comment by micahstairs** [comment]
I'll need to double check the rules about nested execution and the artifact on display.

This will be primarily backend work, but there will be a small amount of frontend work here (e.g. highlight echo text when it's being executed).

**Comment by ultimatefiend** [comment]
One more note on this...the interaction engine needs a way to denote an echo effect for a card, like "<CARDID>E1" or something like that.  If we can agree what that will look like, the cards can be implemented, but can't be tested until the execution of the echo effect is implemented.

**Comment by micahstairs** [comment]
Yes, please use E1!

**Comment by ultimatefiend** [comment]
Chris didn't comment on that, but there is a section in the FAQ that talks about echo effects and the execution effects: https://bgg.cc/thread/1141576/echoes-private-cooperative-dogmas-use

https://tesera.ru/images/items/164885/Innovation%20Echoes%20of%20the%20Past.PDF

**Comment by ultimatefiend** [comment]
But then the instructions say this in the Deluxe version:

Echo effects are also executed when a card’s dogma effects are performed
for a reason other than a Dogma action. Other expansions add various
ways for this to occur, including Endorse and displayed Artifacts,
and many cards cause you to execute another card’s dogma effects. In
all of these cases, echo effects in that card’s color are executed.

**Comment by micahstairs** [comment]
While I'm thinking of it, one thing we need to figure out is whether we still execute echo effects if the card moved before we got the chance to execute its echo effect (because of another echo effect).

**Comment by micahstairs** [comment]
According to a non-authoritative source:

```
When you announce the dogma action, at that moment, which dogma effects happen (including echo effects) are locked down, even if cards are subsequently covered, revealed, or removed. Also, when the dogma action is declared, who shares and is subject to demands is also locked down, even if icons change.
```
https://boardgamegeek.com/thread/2850928/splaying-changes-visible-echoes-and-icon-count-dur

**Comment by ultimatefiend** [comment]
That seems like a reasonable solution.  The rules don't state specifically when the echo effects are locked in.  This would be consistent with how isotropic implements it as well.
