### ISSUE TITLE
Special hex icons need to be rendered in some dogma effects 

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#360]
Some cards (e.g. Loom, red age 6) show an empty black hex icon in the dogma text.  For the moment, this was specified as ${icon_0} where it is needed.

Also, Saxophone Age 7 has a special hex icon in its dogma text (the hex has a note in the middle).

Please add these to hexagon_icons_echoes.png (you could make them the same size as the other hex icons for simplicity, even though we will shrink them in-game).

**Comment by micahstairs** [comment]
Josh did his part, now I'll take care of getting this incorporated into the front-end.

**Comment by micahstairs** [comment]
We can't forget about the Heritage tooltip too.
