### ISSUE TITLE
Add visible bonus icons to the total score for a player

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#361]
The highest bonus is counted at full value.  Every icon after that add one to the score.

So, two 5 bonuses and a 2 bonus would be:

5 + 1 (for the extra 5) + 1 (the 2) = 7

**Comment by ultimatefiend** [comment]
It might also be nice to show the visible icons and their individual contribution.  Isotropic highlights the bonus that is full value and shows the rest of the visible bonuses in a slightly muted color to make it clear which ones have full value.  I don't know if we want to do that, but it is nice from a user's perspective to know the bonus contribution.

This feature is also needed for the cities expansion as well.

**Comment by ultimatefiend** [comment]
I was studying the code for the score update and it looks like the score is only written to the DB when a dogma during an action causes the score to be updated.  So other actions (like tucking or melding) will not result in the score being updated.

For the bonus icons, these can appear (and modify) the score during other types of actions that are not scoring directly.  So I think we will need to recalculate the score every time (or maybe the bonus contribution) when the board changes.

There are some weird cards (like Artificial Heart Age 10) that can temporarily modify the score during a dogma action as well.  I don't know how we would display that.  Maybe the score would go up during the dogma and then return to normal afterwards?

**Comment by micahstairs** [comment]
For Artificial Heart, I wouldn't bother changing the visible score. All that affects is the check for achievement eligibility.
