### ISSUE TITLE
Add promote operation during meld action

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#363]
Promote would allow a player to automatically meld (and optionally execute) a card of lesser or equal value in their forecast when a card is melded.

The promotion would also trigger visible echo effects of the promoted color.

The user would need an option to skip the promotion even if they were eligible and the ability to select their card (possibly using a private viewing window).

**Comment by micahstairs** [comment]
I just added the new states to the diagram. Time to implement this!

<img width="879" alt="Screen Shot 2022-06-11 at 8 14 36 PM" src="https://user-images.githubusercontent.com/7231485/173209030-65996826-5deb-4ba4-87b7-3ec2bb7c76c8.png">

**Comment by micahstairs** [comment]
Ah I didn't account for how we sometimes will be digging before we promote. This graph is going to get messy...

**Comment by ultimatefiend** [comment]
don't forget about the city searching interaction (returning cards that don't match symbols)

If you are redrawing the diagram, you might want to consider how endorsing will work.

**Comment by micahstairs** [comment]
Yeah that's a great idea. I'll consider the city searching interaction at the same time.

Endorsing won't touch the exact same part of the graph (since it doesn't involve melding) so I'll worry about that later.

**Comment by micahstairs** [comment]
I finished updating the state diagram:

<img width="675" alt="Screen Shot 2022-07-01 at 9 48 32 PM" src="https://user-images.githubusercontent.com/7231485/176982240-327bb350-0adc-48db-9b61-2f54753a2cb6.png">
