### ISSUE TITLE
Achieve action needs to calculate eligibility when two or more of the same value achievement are available

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#364]
Basically, if the player already has 1 age 1 achievement, they would need 2 * 5 * 1 for a second age 1 achievement.  This achieve option should be aware of this before displaying the achieve option during the player's turn.

**Comment by micahstairs** [comment]
The eligibility logic is on the backend, but there is some frontend work to do here as well. We need to adjust the tooltips when hovering over claimable achievements, and we also need to think about which achieve buttons we want to show. For example, if there are two Echo 2s and one Base 2, and all 3 are eligible to be achieved, do we actually want to show three buttons for that? Or do we just show one button and clicking it will achieve an arbitrary achievement (forcing them to click on a specific card if they care which achievement they will get). My guess is that most times players won't care which achievement they claim if they are all the same number. Unless they are tracking the movement of cards, they won't know which are which.

**Comment by ultimatefiend** [comment]
Also, Laser does too if I recall correctly.

**Comment by ultimatefiend** [comment]
I'd say one button for the achieve 2 action (which would lead to a choice).  If they are still eligible for the next 2, then that option would pop back up again.

**Comment by ultimatefiend** [comment]
I was thinking they'd have a choice of "Achieve 2", "Achieve 3", etc. and then after they select it, then they'd have an option to select which one they'd want (like how the artifacts choose achievements already).  If, after the first selection, they are still eligible for another achievement of the same value, the option would stay there and be a valid selection until they lose eligibility.

**Comment by micahstairs** [comment]
Okay, but what's the purpose of getting them to click on "Achieve X" if they still need to click on a specific card afterwards? They already have the alternative to click on the achievement directly:

<img width="1274" alt="Screen Shot 2022-04-12 at 3 21 06 PM" src="https://user-images.githubusercontent.com/7231485/163037640-123ea288-6c39-4de7-8adc-dcefe88fb1a0.png">

Personally, I think the best user experience would be as followed: If they don't care which specific achievement they want then they can click on "Achieve X" and we will give them an achievement arbitrarily. If they do care, then they can click on a specific card.

The added bonus of this proposed approach is that it's less work for us. This is already the existing behavior.

**Comment by ultimatefiend** [comment]
Oh yeah, that's totally better.  I didn't realize you could click on achievements already.

**Comment by micahstairs** [comment]
Oh great! Glad we are on the same page now!

**Comment by ultimatefiend** [comment]
I took a look at this and isn't clear how to add in the bonuses to the score.  It looks like the score is tracked by how it changes from one move to the next (i.e. adding/removing cards to/from the score pile).  The bonuses are not moved into a score pile...they become visible by dogma or melding cards so calculating the "delta" would require knowing how many bonuses (and the max value) before and after the dogma.

**Comment by micahstairs** [comment]
> I took a look at this and isn't clear how to add in the bonuses to the score. It looks like the score is tracked by how it changes from one move to the next (i.e. adding/removing cards to/from the score pile). The bonuses are not moved into a score pile...they become visible by dogma or melding cards so calculating the "delta" would require knowing how many bonuses (and the max value) before and after the dogma.

I think you posted that comment on the wrong issue. This has nothing to do with bonuses.

**Comment by micahstairs** [comment]
This work should be done.
