### ISSUE TITLE
Add piles to table for Cities cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#368]
The pink cards shall be present.  The pink cards can also be put in hands, scores, and achievements.

**Comment by ultimatefiend** [comment]
I imagine the ability to draw the Cities cards will be done here as well since their layout is very different than other cards.

**Comment by micahstairs** [comment]
Can you file a separate issue to track rendering the cards? That's a separate piece of work from rendering the piles.

**Comment by ultimatefiend** [comment]
done -> #375
