### ISSUE TITLE
Add on meld effects for City cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#370]
This is from the manual:

![image](https://user-images.githubusercontent.com/11416698/162663078-bb368e16-660b-4a78-92ad-e071f186228e.png)

The search icon will need to be the same as the other icons of the same type, but the search would occur based on the location of that icon (it has to be top center).

The other ones should be pretty straightforward.  We should have some sort of indication for the flag/fountain achievements while they add an achievement to the player's score (i.e. kind of like a card in the achievement pile).

**Comment by micahstairs** [comment]
I like your idea of putting a fake card in the achievement pile to indicate the extra achievement. However, that's more of a nice-to-have, so I don't think we'd need to focus on effort on it anytime soon.

Also, the tooltip which appears when hovering on a card before meld needs to be updated to indicate what "on meld" actions will occur.

**Comment by micahstairs** [comment]
Closing this since the basic (untested) functionality is in place. The tooltip updates are a nice-to-have and we can tackle that much farther in the future.
