### ISSUE TITLE
Add Endorse action option when the conditions are met

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#371]
Not sure what this would look like exactly, but I imagine there will be an option to endorse a top card (could have a maximum of 4 top cards that could be endorsed for a given city) if the criteria is satisfied:

1)  A city with a matching icon to the dogma effect of another top card
2)  A card in hand of less than or equal value to the city (symbols on the card are not relevant)
3) An endorsement hasn't already happened this turn.

This option would be an addition to any meld, dogma, or achievement actions that would be possible.

**Comment by micahstairs** [comment]
Maybe they could click on the card and then afterwards they will be prompted with whether they want to endorse it or not?

We'd also need to make sure we make some changes to the tooltips which appear when you hover over before dogma-ing the card.

**Comment by ultimatefiend** [comment]
That's an interesting idea, but kind of late to make that decision perhaps?   The player may not select a card to dogma if they knew another card could be endorsed.

**Comment by micahstairs** [comment]
Maybe we will have to provide another visual cue that the card can be endorsed? Maybe by highlighting it with a different color than the usual color used to indicate clickable cards?
