### ISSUE TITLE
Render the Cities cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#375]
This will require an update to the database (two new icon spots!).

There are also a number of new icons for the on meld effects.

The title is also in a different location than the other innovation cards.

The "missing" hexes are always in the top right corner and have a shared image across the entire age (with just a color adjustment).

**Comment by ultimatefiend** [comment]
When a normal icon appears in the top middle, it will always be a "search" action.

**Comment by ultimatefiend** [comment]
This is the spot numbering in the database.

![image](https://user-images.githubusercontent.com/11416698/163598550-f2092768-2969-4d85-a7be-478f2cd5df61.png)

**Comment by micahstairs** [comment]
<img width="770" alt="Screen Shot 2022-05-16 at 6 58 34 AM" src="https://user-images.githubusercontent.com/7231485/168578455-5896fd9b-b958-4957-91b1-7ff94288fb22.png">

**Comment by ultimatefiend** [comment]
is this done?  I imagine the hexagon icons are the only thing that is left?

**Comment by micahstairs** [comment]
I think hexagon icons and search icons are probably the main things left?
