### ISSUE TITLE
Test what happens when a player is eliminated and the page is refreshed

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#388]
If a player is eliminated and the page is refreshed, does their board zone re-appear, or does it stay disappeared?

Ideally, the board wouldn't come back, but I suspect it will. Can someone confirm this?

**Comment by ultimatefiend** [comment]
it comes back.

![image](https://user-images.githubusercontent.com/11416698/163700120-53120da7-053e-4dab-9095-122b11c470b2.png)

You can see it at the very bottom.
