### ISSUE TITLE
Test that special achievements can't re-enter the game

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#389]
We need to confirm that special achievements aren't granted after they've been removed from the game. While looking at the code a few weeks ago, I think I saw that there might be a bug in checkForSpecialAchievementsForPlayer.

**Comment by ultimatefiend** [comment]
How can special achievements be removed?

**Comment by micahstairs** [comment]
Exxon Valdez removes achievements when eliminating a player.

**Comment by ultimatefiend** [comment]
ah ok

**Comment by ultimatefiend** [comment]
They aren't in the game, but you get an error:

Unexpected error: Error while processing SQL request (Localhost via UNIX socket): UPDATE card SET position = position - 1 WHERE owner = 0 AND location = 'removed' AND position > You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7 (reference: GS1 19/04 01:25:08)

**Comment by ultimatefiend** [comment]
This happened when trying to re-achieve universe:

![image](https://user-images.githubusercontent.com/11416698/163892467-102a7a2d-85e3-433a-b85c-a13a251d80ea.png)
