### ISSUE TITLE
30 World Cup Final Ball returns relics

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#390]
From looking at the implementation, it isn't obvious that we are stopping the player from clicking on a special achievement.

If there is a bug here, we should confirm that there isn't a bug in any similar cards.

**Comment by ultimatefiend** [comment]
hmm...probably should check relics too

**Comment by ultimatefiend** [comment]
I'm pretty sure I checked specials, but I will double check.

**Comment by ultimatefiend** [comment]
It returns relics but does not affect special achievements.

**Comment by ultimatefiend** [comment]
I think the non-null age of relics is causing the problem.

**Comment by micahstairs** [comment]
Is it actually a bug that players can select relics here?

**Comment by micahstairs** [comment]
I found https://boardgamegeek.com/thread/1811482/article/27436133#27436133. Carl seems to say that relics should not be selectable here.

**Comment by micahstairs** [comment]
The fix I just pushed for this involved the assumption that players never need to select relics. However, I just realized that players may need to select relics if they have to return their whole hand, for example. So I still need to wire in proper support for this.

**Comment by ultimatefiend** [comment]
if you have a single relic, it will select it automatically and return it (at least that's what happened last night).  If your change will prevent that from happening, I think we are all set here.

**Comment by micahstairs** [comment]
My change will prevent that from happening, but there are situations where they still need to be able to click on it, so there's still work to be done.
