### ISSUE TITLE
Audit whether there are other cards which need to reveal hands

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#393]
We need to go through all of the base and artifact cars and see if there are cards similar to Oars which requires we reveal the hand.

**Comment by micahstairs** [comment]
I finished auditing the base cards:
- [ ] Machinery (age 3) should reveal the card before scoring, since it needs to have a castle.
- [ ] Feudalism (age 3) should reveal the opponent's hand if they are unable to transfer a card with a castle.
- [ ] Classification (age 6) should reveal the opponent's hand after taking all cards of a particular card from their hand.

**Comment by micahstairs** [comment]
Once I finish the audit of the Artifact cards, we will need to make a decision. Does it actually make sense to give full information about cards or should we try to reduce information overload?

**Comment by micahstairs** [comment]
I've audited Artifacts (only audited up to the end of age 4 so far):
- [ ] Papyrus of Ani (age 1) should reveal the hand if they are unable to return a purple card
- [ ] Xianrendong Shards (age 1) should reveal the scored cards before scoring them (otherwise other players can't confirm they were the same color)
- [ ] Mask of Warka (age 1) is a weird case. It specifically says only to reveal cards of a specific color, however, how can players prove they are showing all of that color unless they show their whole hand?
- [ ] Ark of the Covenant (age 1) should reveal the returned card so that other players can see the color
- [ ] Molasses Reef Caravel (age 4) should reveal the hand if there are no blue cards to meld
- [ ] Delft Pocket Telescope (age 4) is a weird case. It specifically says only to reveal one of the drawn cards with a symbol in common with the returned card, but shouldn't both cards be revealed if you were playing this in real life? Also the returned card should probably be revealed too.

**Comment by ultimatefiend** [comment]
I don't think Delft needs to reveal both cards.  I think the point is that you can keep one of them a secret even if they match the symbols.  Revealing the card from the score pile would make sense though so the opponent knows whether a symbol matches or not.

If nothing matches, then both cards should be revealed to confirm that no symbols match.

**Comment by lordmcfuzz** [comment]
I agree with @ultimatefiend's read on Delft

As for Hansen Writing Ball Yeah if we were only talking about 1v1 we don't have to do anything, but any multiplayer game, the hand should be revealed before if they were unable to meld a blue card.

**Comment by micahstairs** [comment]
Thanks for the input! Okay, here is my proposal:

- Machinery: Reveal card before scoring. Reveal hand if no cards can be scored.
- Feudalism: Reveal hand if no cards can be transfered.
- Classification: Reveal hand after transferring.
- Papyrus of Ani: Reveal the purple card before returning. Reveal the hand if no purple cards.
- Mask of Warka: I'd prefer not to reveal both the purple and non-purple cards from every player's hand because I think it will just add confusion to the logs. Besides, the mechanics of the card incentivizes players to reveal all of the purple cards that they have.
- Ark of the Covenant: Reveal the card before returning.
- Molasses Reef Caravel: Reveal the hand if there are no blue cards to meld
- Delft Pocket Telescope: Reveal the card before returning. If there are no matching symbols on the drawn cards, reveal them before returning.
- Puffing Billy: Reveal the card before returning.
- Hansen Writing Ball: Reveal hand if there are no blue cards.

Any objections here? I think the only one which might be controversial is Mask of Warka.

**Comment by ultimatefiend** [comment]
I agree with your take on Mask of Warka.  The whole hand needs to be revealed.  You could use the Mask to check for cards in your opponent's hand (like Machinery for example) even if you didn't think you could get the achievement.

**Comment by micahstairs** [comment]
Did you mean to say "disagree"? My proposal was only to reveal purple cards since I think it would be otherwise confusing to tell which revealed cards are purple and which aren't, unless the player hovers over the card name.

**Comment by micahstairs** [comment]
Ooh I have an idea for Mask of Warka. I'll get player to reveal their hand, immediately followed by something that says "They revealed X purple cards". Rather than re-iterating the list of purple cards

**Comment by ultimatefiend** [comment]
Delft: I think the card from the score pile needs to be revealed as well.  Otherwise, the opponent couldn't tell whether any symbols match.

**Comment by micahstairs** [comment]
Yup! I have that in the proposal already.
