### ISSUE TITLE
Along the River says a yellow card is melded when it is actually tucked

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#394]
Not sure why this is happening, but here is the log:

You draw 10 Databases.
Sharing bonus.
You score 4 Enterprise.
You draw and reveal 4 Enterprise.
You have to execute the non-demand effect.
**kahliadev0 melds 4 Perspective.**
kahliadev0 draws and reveals 4 Perspective.
kahliadev0 places 4 Gunpowder in their hand.
kahliadev0 draws and reveals 4 Gunpowder.
The non-demand effect applies on kahliadev0.
You have 3 .
kahliadev1 has 0 .
kahliadev0 has 4 .
You activate the dogma of 3 Along the River during the Qingming Festival with  as the featured icon.

**Comment by ultimatefiend** [comment]
Colonialism (another draw and tuck card) doesn't do this.

**Comment by micahstairs** [comment]
The same thing happens with Hansen Writing Ball.

Turns out this was a missing 'revealed->board' case. This is an easy fix.
