### ISSUE TITLE
Restore icons on player panel

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#396]
I think your recent changes broke the player panel:
<img width="189" alt="Screen Shot 2022-04-17 at 7 15 01 PM" src="https://user-images.githubusercontent.com/7231485/163735712-d166f14f-d5e0-44cf-be07-a942c7266b7f.png">

We are missing some icons there (e.g. max age on board).

**Comment by lordmcfuzz** [comment]
Did I re-break this?

**Comment by micahstairs** [comment]
Not to my knowledge. You just didn't link this issue to the PR.
