### ISSUE TITLE
Try to vertically center icons within dogma text

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#398]
<img width="479" alt="Screen Shot 2022-04-17 at 7 20 50 PM" src="https://user-images.githubusercontent.com/7231485/163735850-7bb95539-0442-4b99-a2bd-9ebd57cbedbc.png">

I wonder whether using `vertical-align: middle;` would improve the overall look of how we render icons on dogma text. Without vertically centering them, I find that the icons seem large.

**Comment by micahstairs** [comment]
It's definitely closely related. You would have a better idea if it's already been addressed or not.

**Comment by lordmcfuzz** [comment]
was this fixed with some of the work you did right before release time?

**Comment by micahstairs** [comment]
I'm happy with the current state so I'll close this.
