### ISSUE TITLE
Prevent autoselection from revealing hidden information

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#402]
I've noticed several cards where the new autoselection mechanism reveals hidden information. There's still some investigation required to nail down exactly what needs to be changed. For example, autoselection currently causes Papyrus of Ani to reveal when the player only has one purple card in their hand.

**Comment by ultimatefiend** [comment]
hmm...it will need to be an interaction option I think.  Like "autoselection" => true/false or something like that

**Comment by micahstairs** [comment]
I think I can tweak the generalized logic to get us close, and then we can use autoselection=false to help with a few of the edge cases. Good idea!

**Comment by micahstairs** [comment]
Also if this isn't working quite right by the time we want to do a public release, we could hold back this feature since the logic is very isolated and easy to turn on/off.

**Comment by ultimatefiend** [comment]
We will have Echo effects with a similar idea like candles.

**Comment by ultimatefiend** [comment]
There are certain cases where the information is based on public information (like Domestication), but other times it is not (like symbols on cards in your hand).  I guess that is the real difference.  Age numbers are always public, but the other attributes are not (like symbol information) if they aren't revealed or on a board.

**Comment by micahstairs** [comment]
The card's type is also public information (and whether or not it is a relic but I don't think that ever matters for autoselection).
