### ISSUE TITLE
Interaction needed for returning cards from the "Search" on meld effect

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#403]
Currently there isn't a way to have an interaction during a meld, but the "Search" icon needs to allow the user to determine the order in which cards are returned if they don't match the searched icon.

Also, if the state diagram needs to be updated, probably should consider the effect of Promotion (from Forecast and also an on meld effect) and the endorse action.

**Comment by ultimatefiend** [comment]
For now, the cards will be returned in the order they were drawn for the Search action.

**Comment by micahstairs** [comment]
I'm planning to find a way to re-use the existing card selection engine, so that we can take advantage of the existing interactions and automations. I believe this will just require some clever fiddling of the game state engine.
