### ISSUE TITLE
Create spritesheet of card backgrounds for Cities

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#406]
Let's create a new spritesheet for the Cities backgrounds (instead of adding them to the existing spritesheet).

To simplify things this time, I'm going to propose we leave the colorblind indicators (where the age number goes) on the image files, instead of surgically removing them and then re-adding them using ImageMagick.

This blocks some of the work in #375.

**Comment by normaljosh** [comment]
I think it was @TADodger who extracted the backgrounds from the original cards. Could we see if they or someone else can complete that part of this issue? I might be able to manually do it using photopea but it would take me a long time.

**Comment by micahstairs** [comment]
Oh I forgot it wasn't you, sorry!

@TADodger are you interested in doing the image manipulation part of this task?

**Comment by micahstairs** [comment]
Actually I've already got 3 of the backgrounds done! I had some time on my flight.

**Comment by micahstairs** [comment]
@normaljosh I finished prepping the card backgrounds. Do you mind building the spritesheet?

**Comment by normaljosh** [comment]
Wow, I'm impressed that you were able to make these on a flight, my hands are not that steady!
