### ISSUE TITLE
Revise calculations for placement of score and forecast zones

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#422]
When I added the forecast zone to the UI, I didn't spend any time getting the calculations right. Ideally there would be one card's worth of space between the two zones.

We also need to make sure that when Echoes is disabled that the forecast zone is removed from the board and the calculations still make sense.

We also need to make sure the layout looks good on both desktop and mobile.

**Comment by ultimatefiend** [comment]
it sits a little low on the player board.  Was that intentional:

![image](https://user-images.githubusercontent.com/11416698/166085930-6d29fe30-929e-4e28-8029-3f5d506bc1c6.png)

**Comment by micahstairs** [comment]
You need to force refresh your page.

**Comment by ultimatefiend** [comment]
Ah yes, that helped.  There is an offset with the scorepile though:

![image](https://user-images.githubusercontent.com/11416698/166121073-90ecf824-0175-4d0e-ace6-c63419094197.png)

**Comment by micahstairs** [comment]
Yeah I saw the same offset but couldn't quickly figure out a fix. I was focusing my time on just getting the zones functional haha.

**Comment by micahstairs** [comment]
Here's a screenshot to capture the weird overlap that's happening:

<img width="826" alt="Screen Shot 2022-10-23 at 8 21 07 PM" src="https://user-images.githubusercontent.com/7231485/197425666-3769ac0c-270d-4ecc-b06e-8b5abc3b7133.png">

**Comment by micahstairs** [comment]
Before closing this, I need to shrink the achievement zone to a width of 2 cards on mobile when the forecast is present.

**Comment by micahstairs** [comment]
![Screenshot_20221207-171943](https://user-images.githubusercontent.com/7231485/206309120-538922ac-40db-4672-bb08-2da1d9f46762.png)

**Comment by micahstairs** [comment]
For some reason the score and forecast zones keep alternating between 2 and 1 cards. This is the last thing we need to fix.

**Comment by micahstairs** [comment]
@lordmcfuzz I'm taking this back! I see the problem and will fix it.
