### ISSUE TITLE
bottom_from draw option doesn't update the rest of the pile with their new position

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#434]
This causes problems on the front end.

**Comment by ultimatefiend** [comment]
It might be useful to make this a generic property for an interaction.  THere are a number of cards that target the bottom of piles (scissors, plumbing, etc.)

**Comment by micahstairs** [comment]
Yup! This would be a generic behavior whenever bottom_from is being used.

**Comment by ultimatefiend** [comment]
oh, i didn't realize it opens up that avenue as well...very interesting.

**Comment by micahstairs** [comment]
So I just tested chopsticks and the database state looks fine to me and also I'm not getting any frontend errors. I'm not sure how to replicate the issue you were seeing.
