### ISSUE TITLE
Monument not counting during free action?

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#437]
Here is the game replay...

https://studio.boardgamearena.com/1/innovationdev?table=375246

I scored 8 cards during my turn with hudson's bay (during my free action) and currency combined and did not receive monument.  It looks like Hudson's bay is using the right function under the hood for scoring cards.

This is the log sequence:

You draw and score 3 Translation.
You draw and score 3 Compass.
You draw and score 2 Road building.
You returned cards of three different values.
No more card matches the criteria of the effect.
You return 5 Societies from your hand.
You return 4 Colonialism from your hand.
You return 3 Translation from your hand.
You have to execute the non-demand effect.
lordmcfuzz0 has 2 .
You have 7 .
You activate the dogma of 2 Currency with  as the featured icon.
You return 5 Hudson's Bay Company Archives from your display.
You splay your yellow cards right.
You meld 1 Agriculture from your score pile.
12:14 PM
You score 3 Feudalism from your board.
Your yellow stack is reduced to one card so it loses its splay.
You score 1 Agriculture from your board.
You score 1 Sailing from your board.
You score 3 Mjolnir Amulet from your board.
You score 1 Pottery from your board.
You have to execute the non-demand effect.
lordmcfuzz0 has 2 .
You have 11 .
You activate the dogma of 5 Hudson's Bay Company Archives with  as the featured icon.

**Comment by micahstairs** [comment]
Oh great catch! We might be resetting the score/tuck counters at the beginning of the first action. We will need to look at the code to confirm.

**Comment by micahstairs** [comment]
I checked the code and it's actually being reset at the end of the turn (see where resetFlagsForMonument is called), so I don't have an explanation for why you saw this bug. Are you sure the Monument wasn't already achieved?

**Comment by micahstairs** [comment]
I confirmed that both Hudson's Bay Company Archives and Currency actually increment the score counter in the DB and I also confirmed that they are incremented during the free action.

**Comment by ultimatefiend** [comment]
If you follow the game replay, it was never claimed.  This was in InnovationDev and not the alpha if that makes a difference.

**Comment by ultimatefiend** [comment]
I just recreated it in innovationdev with the same conditions and it did the same thing.

**Comment by micahstairs** [comment]
I'm not able to open your replay, but thanks for confirming you could replicate it! I'll try to replicate it myself.

**Comment by ultimatefiend** [comment]
actually, i can't achieve monument at all.

**Comment by ultimatefiend** [comment]
if ($achievement['owner'] != 0 || $achievement['location'] = 'removed') {
                continue;
            }

missing an =

**Comment by micahstairs** [comment]
Ah the bug slipped in here: https://github.com/micahstairs/bga-innovation/commit/1c2fc09c79da1851ede30dbb299cca6bf8e5d4c5
