### ISSUE TITLE
Add ability to select more than one age at a time in an interaction

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#447]
This is specific to Homing Pigeons at the moment, but may apply elsewhere.

If the interaction needs to select multiple cards and they need to be of different ages, then this would be necessary.  This is the attempted interaction that returns an error:

            $options = array(
                'player_id' => $player_id,                
                'n' => 2,
                'can_pass' => false,
                
                'owner_from' => $player_id,
                'location_from' => 'score',
                'owner_to' => 0,
                'location_to' => 'deck',
                
                'age_array' => self::getAuxiliaryValueAsArray(),
            );

That's what I tried for Homing Pigeons and it doesn't work.  'age' doesn't work either if passed as an array.

**Comment by micahstairs** [comment]
You're correct that we currently do not have anything which can support this. The closest we have is `min_age` and `max_age` but that only works for a consecutive range of ages, so it doesn't appear to be helpful for any of these cards.

It will be pretty straight-forward to add this functionality though.

**Comment by ultimatefiend** [comment]
could we use min_age with safety pin?  It seems like that should work?

**Comment by micahstairs** [comment]
Ah yes, please do that!

**Comment by micahstairs** [comment]
I took a look at the code, and this change isn't going to be as clean as I had hoped. I'll probably focus my attention on other things for the time being.

**Comment by ultimatefiend** [comment]
I would say that this looks good now.
