### ISSUE TITLE
Transferring from forecast doesn't seem to work properly

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#448]
I attempted this via Almanac and it doesn't do the transfer:

           // First reveal the card to prove that it has a bonus.
            $options = array(
                'player_id' => $player_id,
                'n' => 1,
                'can_pass' => true,
                
                'owner_from' => $player_id,
                'location_from' => 'forecast',
                'owner_to' => $player_id,
                'location_to' => 'revealed',
                
                'with_bonus' => true,
            );
            break;

and it does this:

![image](https://user-images.githubusercontent.com/11416698/168287338-e11adabb-f936-4dd6-a885-318726a4374d.png)

There is a card in the forecast with a bonus when this happens.

**Comment by micahstairs** [comment]
I found a bug in your PR in encodeLocation() which may or may not fix this, I'm not sure.

**Comment by ultimatefiend** [comment]
this should be fixed in the age 4 PR i just submitted.
