### ISSUE TITLE
Double-check that all of the Artifact icons are correct

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#454]
We should cross-reference each rendered Artifact card with a printed version of the game to confirm that all of the icons are correct.

- [x] Age 1
- [x] Age 2
- [x] Age 3
- [x] Age 4
- [x] Age 5
- [x] Age 6
- [x] Age 7
- [x] Age 8
- [x] Age 9
- [x] Age 10
- [x] Relics

**Comment by ultimatefiend** [comment]
this should be good now.
