### ISSUE TITLE
Clear up confusion about when special achievements are awarded

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#462]
Many players have voiced confusion (https://boardgamearena.com/bug?id=62821) about when special achievements are awarded (as a result of us changing the timing of the special achievement check, after consultation with Chris). 

I'm in the process of emailing back and forth with Chris to reach a resolution on this.

We definitely need to get this story straight before we can release the expansion.

**Comment by micahstairs** [comment]
Marking as blocked until I get a response back from Chris.

**Comment by micahstairs** [comment]
I just sent another email. I'm trying to reach a resolution soon on this.

**Comment by micahstairs** [comment]
Finally got a response. He agreed with my proposal:

```
- Remove the word "immediately" from all of the base special achievements except for Monument. Similar to the special achievements in Cities, it will confuse players more if Monument isn't awarded the instant they finish scoring or tucking 6 cards.
- Keep the timing of the other special achievements to check at the end of the effect
```

**Comment by ultimatefiend** [comment]
so does that mean Glory and Victory are awarded immediately or not?  I'm not clear on that.

**Comment by micahstairs** [comment]
I think we want to award those immediately! We only want to wait for achievements which depend on examining the board state.

**Comment by ultimatefiend** [comment]
Those will be easy then.  I like it.
