### ISSUE TITLE
Spectators don't see the extra symbols while dogma'ing an artifact on display

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#468]
![image](https://user-images.githubusercontent.com/11416698/169420289-a1540eaf-7f84-4650-8b37-1ee5ab1a78eb.png)

**Comment by micahstairs** [comment]
Nice find! I'll classify this as a bug, but I don't necessarily think this needs to be release-blocking?

**Comment by ultimatefiend** [comment]
yeah I would say this isn't release blocking.

**Comment by ultimatefiend** [comment]
wait, are the extra symbols removed after the dogma begins?

**Comment by micahstairs** [comment]
Yup! That's intentional, otherwise it gets confusing because some cards refer to the number of symbols in the effect and the display is not supposed to be counted.

**Comment by ultimatefiend** [comment]
Ok, that's working fine then. :)
