### ISSUE TITLE
Confirm behavior of Barometer's second dogma effect with Carl

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#473]
The current wording is imprecise regarding when the blue card needs to be revealed (or even how many), so it will be implemented like so until we are told otherwise:

"You may reveal and return a blue card from your forecast. If you do, claim the Destiny achievement and return all cards from your forecast."

Since it is different than how the card describes this interaction, we should ask Carl if this interpretation is ok.

**Comment by micahstairs** [comment]
We plan on asking about this proposed rewording on BGG (mentioning specifically that we want to reword it on the BGA adaptation).

**Comment by micahstairs** [comment]
I just sent an email to Chris.
