### ISSUE TITLE
Clarify interpretation of Tuning Fork's echo effect

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#480]
The text says :

Look at the top card of any deck, then place it back on top.

Does this mean that you can look at any of the decks on the table or is it a draw and return (like daily courant)?

**Comment by ultimatefiend** [comment]
I'm going to treat this like Daily Courant where you draw the card to hand and then put it back on top.  So they can "look" at it while its in their hand.  I'm hoping the card id interaction that was added recently will let me select a pile on the table.  If so, it should be pretty easy to loop through every pile on the board (which will vary based on the expansions on the board).

I guess the other open question is a pile that is otherwise not drawable (an age where the base cards are exhausted) be drawable with this echo effect?  In other words, if there are no base 2s left, can they look at the top of the pile of echo 2s?

**Comment by micahstairs** [comment]
Hmm I think it's worth getting clarification on this before we try to implement it, since there's a chance we will get it wrong.

**Comment by micahstairs** [comment]
Actually I just found this: https://boardgamegeek.com/thread/957672/article/11915291#11915291.

**Comment by micahstairs** [comment]
From Chris: "any deck, even if there's an empty base." He also added the same comment to https://boardgamegeek.com/thread/957672/article/11915291#11915291.
