### ISSUE TITLE
We should cross-reference each rendered Base card with a printed version of the game to confirm that all of the icons are correct.

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#488]
Technically we didn't change any of the icons in the database for the base cards, but there's still the chance we could find some incorrect icons.

The reason for this is because before the graphic refresh, the cards were rendered using full images (given to us by the publisher), but now we dynamically build the cards, so if there were any existing bugs, they are way more obvious now!

- [x] Age 1
- [x] Age 2
- [x] Age 3
- [x] Age 4
- [x] Age 5
- [x] Age 6
- [x] Age 7
- [x] Age 8
- [x] Age 9
- [x] Age 10

**Comment by ultimatefiend** [comment]
No issues here.  I looked at them and they all check out.

**Comment by micahstairs** [comment]
Amazing thanks!
