### ISSUE TITLE
Hot Air Balloon requires the ability to select specific cards on other player's boards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#489]
This is the card text:

You may achieve (if eligible) a top card from any player\'s board if they have an achievement of matching value. If you do, transfer your top green card to that player\'s board. Otherwise, draw and meld a ${age_7}.

The first part of being able to select a specific card of a specific value on other player's boards isn't covered currently.  Charter of Liberties lets you select splayed piles on other boards (for example), but doesn't allow the selection of specific ages.

In this case, the ages are limited to the achievement ages that a specific player has (these numbers will be different based on what each player has achieved).

**Comment by micahstairs** [comment]
Hmm maybe I will need to add a special "matches_achievement_value" option.
