### ISSUE TITLE
NULL icons are being counted as a hexagon icon

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#490]
This wasn't relevant until Echoes where the hex icons are counted towards a special achievement.

This gave me heritage so the NULL icons must be counted with the empty hex icons.  This will be a problem for Loom as well.

![image](https://user-images.githubusercontent.com/11416698/172073814-ef4abcf3-aa02-4eb8-90b6-65421e58549f.png)

**Comment by micahstairs** [comment]
I expect the countIconsOnCard function needs to use === instead of ==>

**Comment by ultimatefiend** [comment]
This should be fixed now.
