### ISSUE TITLE
Add feature for selecting bottom cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#497]
Several cards (such as plumbing, and scissors) require the user to select bottom cards as part of an interaction.

In most cases, we can make the interaction happen with workarounds, but it would be better if the player could select the cards directly.  I imagine this would be similar to what happens with skyscrapers where it automatically shows all of the cards when cards are being returned.

**Comment by ultimatefiend** [comment]
Example elevator implementation:

            $top_card = self::getTopCardOnBoard($player_id, 2); /* green */
            $bottom_card = self::getBottomCardOnBoard($player_id, 2); /* green */
        
            $options = array(
                'player_id' => $player_id,
                'n' => 1,
                'can_pass' => false,

                'owner_from' => $player_id,
                'location_from' => 'pile',
                'owner_to' => $player_id,
                'location_to' => 'score',
                
                'card_id_1' => $top_card['id'],
                'card_id_2' => $bottom_card['id'],
                
                'score_keyword' => true,
            );

**Comment by micahstairs** [comment]
I notice that you aren't telling it which pile/color to select? That might be why it's not working?

**Comment by ultimatefiend** [comment]
hmm...let me give that a shot.

**Comment by ultimatefiend** [comment]
It works for Elevator.  Adding the color was key.  I guess it won't work for the other cards that need to select a bottom card (like Plumbing and Scissors).

**Comment by ultimatefiend** [comment]
this feature would be a lot like publications actually as that flattens out all of the piles.  I guess the bottom selection option only needs to reveal the bottom cards from each pile though.  The other cards aren't that relevant.

**Comment by micahstairs** [comment]
I expect that flattening the entire stack would be easier to so, and less confusing to players.

**Comment by micahstairs** [comment]
Note to self: To flatten the piles, we do something like:

```
for(var color=0; color<5; color++) {
    var zone = this.zone.board[this.player_id][color];
    this.setSplayMode(zone, zone.splay_direction, full_visible=true); // Show all cards
}
```
