### ISSUE TITLE
Radio Telescope needs a way to select more cards

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#503]
Radio Telescope (age 8) can draw cards that scales with the number of bulbs on your board (which could be significant).

At the end, a single card is selected from the list of cards and melded.  Currently, 3 cards can be selected and remembered (via card_id_x).  This needs to be enhanced for this card to be implemented (or a different solution needs to be implemented).

**Comment by ultimatefiend** [comment]
it might make sense to have a different location...sort of like "revealed", but you don't reveal.  It would also be considered part of the hand, but would only be visible to the player.  This could also be used for lever as well

**Comment by micahstairs** [comment]
That's a neat idea! Should it behave the same as the revealed zone (except that it isn't actually visible to other players)? If so, will players think we are accidentally revealing their cards?

**Comment by ultimatefiend** [comment]
hmm good point.  the log should be clear that the cards aren't being revealed....or maybe it is more like a subset of the hand?  maybe it appears in a horizontal line above your hand or something like that.

**Comment by ultimatefiend** [comment]
the other player wouldn't need to see what is going on at all.  it could be local to the current player.
