### ISSUE TITLE
Implement the Safety Pin Relic

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#505]

**Comment by ultimatefiend** [comment]
#447 is needed.  We could also loop through each age 7 and above if needed.

**Comment by micahstairs** [comment]
This is not blocked. The min_age/max_age feature will suffice.

**Comment by ultimatefiend** [comment]
I don't see the minmax option anywhere in the game.php file.  Can you point me to it?

**Comment by micahstairs** [comment]
Take a look at Pottery! I guess the options are called `n_min` and `n_max`.

**Comment by ultimatefiend** [comment]
That's number of cards returned, not the age.

I suspect this new table feature might solve this one as well.  We just need an interaction that lets you select all of the ages.

**Comment by ultimatefiend** [comment]
It works!  I will have a PR soon...
