### ISSUE TITLE
Add table-based auxiliary value in order to store long lists of integers

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#514]
This will be used by cards like Lever. This will also be used by cards like Radio Telescope once we add some sort of option to tell the interaction to select all cards IDs in the table.

**Comment by ultimatefiend** [comment]
I see.  I can see two possible interactions that would be useful:

1.  Allow a user to select all of the card ids in the list regardless of where they are.  This could be helpful for Hot Air Balloon. #489
2. Allow repeat age selections (crossword/lever).  This would make that interaction more natural.

**Comment by micahstairs** [comment]
The only possible outstanding piece of work is the part you had about "Allow repeat age selections (crossword/lever). This would make that interaction more natural."

However, I'll close this, and we can file a separate issue for that if we want to make that improvement.
