### ISSUE TITLE
Create spritesheet with 1st edition colorblind indicator shapes

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#528]
We need a small spritesheet (in order: blue, red, green, yellow, purple) with the 5 color blind indicators from the 1st edition.

https://github.com/micahstairs/bga-innovation/blob/main/img/Innovation_cards.jpg

Please name the generated spritesheet `simplified.jpg`

**Comment by micahstairs** [comment]
@lordmcfuzz do you want these right on the background image you started making instead of making a spritesheet?

**Comment by lordmcfuzz** [comment]
Yeah I plan to just do the photo shop into the background when I can get an
hour or two of free time that is not a sweat shop temp in my office

**Comment by micahstairs** [comment]
I'll close this then.
