### ISSUE TITLE
Moses (Artifacts Age 4) second effect only scores a card from the player's board

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#532]
There is room for interpretation that the Moses card should score cards from any player's board.

```
151 => array('name' => clienttranslate('Moses'),
    'i_demand_effect_1' => clienttranslate('${I compel} you to transfer all top cards with a ${icon_1} from your board to my score pile!'),
    'i_demand_effect_1_is_compel' => true,
    'non_demand_effect_1' => clienttranslate('Score a top card with a ${icon_1}.'),
),
```

It doesn't say this specifically though.

https://boardgamearena.com/bug?id=68170

**Comment by micahstairs** [comment]
I posted a question in an attempt to get a clarification from Carl: https://boardgamegeek.com/thread/2901660/some-cards-arent-clear-whose-top-cards-are-being-r.

He's usually pretty responsive so let's give him a couple days to respond before we make any changes.

**Comment by ultimatefiend** [comment]
We did it correctly according to Carl's response.
