### ISSUE TITLE
Special achievement text not visible on mobile

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#533]
"Mouse over" doesn't really exist on mobile so it is difficult to tell what special achievements are available or in a player's achievement pile.

This was mentioned in a forum post (but not a bug report).

A good solution would be to imitate what other games do when trying provide details on cards like in Agricola:

![image](https://user-images.githubusercontent.com/11416698/180652500-952a8552-5347-4c3e-a098-609bf47cd16d.png)

There is a button to provide details on the card.  This would work with the specials because nothing happens when you click on a card in normal situations.

**Comment by micahstairs** [comment]
You can actually press and hold to make it appear, but I agree there's room for improvement here.

**Comment by micahstairs** [comment]
For the record, this was later filed as a bug report (https://boardgamearena.com/bug?id=68916).
