### ISSUE TITLE
Make Tools card easier to use correctly

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#54]
A lot of players have trouble playing the Tools card correctly. See https://boardgamearena.com/bug?id=18164.

The generally agreed upon fix is to make it so that players choose all 3 of their cards for the first effect before any of them are returned. This will make it so that players don't return a 3 thinking that they are returning it as part of the 2nd effect when it is really being returned for the 1st effect.

If you're interested in taking on this feature request, please do so! This will likely be good practice for when it comes time to implementing cards effects from expansions.

**Comment by micahstairs** [comment]
This would be best implemented using a new `multiselect` boolean field in the options array, which defaults to false if it is unset. That way we could easily apply it to other cards or situations in the future.

**Comment by hildrum** [comment]
I'll take this one.

**Comment by micahstairs** [comment]
Great! I just assigned it to you. This is a pretty tricky change so good luck!

**Comment by ultimatefiend** [comment]
I realized that this multi select feature will be useful for Echoes as well.  Ice Skates and Magnifying Glass have similar multi-select concepts.

**Comment by micahstairs** [comment]
Instead of multi-select, a simpler approach is to show a warning box if they are choosing a 3 as part of the first interaction. See #319 where we are brainstorming similar improvements for other cards.

**Comment by micahstairs** [comment]
I have a PR out for this: https://github.com/micahstairs/bga-innovation/pull/567
