### ISSUE TITLE
Fix special achievements pile which now contains achievements from Cities and Echoes

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#572]
<img width="513" alt="Screen Shot 2022-09-04 at 3 08 06 PM" src="https://user-images.githubusercontent.com/7231485/188329636-cc8e1253-3246-4ab0-81d3-81676ddfbeb8.png">

There's 3 main things that need to be done here:
1) The special achievements are ordered incorrectly in the spritesheet (which will make the next step more complicated)
2) We need to update the SCSS/CSS in order to add the right icons on the right special achievements (we can ignore the icons in the tooltip for now)
3) We need to update the JS logic which places the cards on the screen

**Comment by ultimatefiend** [comment]
also don't forget to do the rotation when they are achieved.  I don't know if that happens automatically or not.

**Comment by micahstairs** [comment]
The rotation happens automatically!
