### ISSUE TITLE
Transcribe Age 1 cards of Artifacts expansion

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#58]
It's time to begin transcribing the cards for the first expansion we want to implement!

For now, let's place these transcribed files in a text file called `artifact_card_effects.txt` in a new `misc/card_transcriptions` directory.

For example, here are some transcribed cards from the base set (see [here](https://github.com/micahstairs/bga-innovation/blob/main/src/material.inc.php) for more example):
```
0 => array('name' => clienttranslate('Pottery'),
    'i_demand_effect_1' => null,
    'non_demand_effect_1' => clienttranslate('You may return up to three cards from your hand. If you returned any cards, draw and score a card of value equal to the number of cards you returned.'),
    'non_demand_effect_2' => clienttranslate('Draw a ${age_1}.'),
    'non_demand_effect_3' => null,
    'achievement_name' => null,
    'condition_for_claiming' => null,
    'alternative_condition_for_claiming' => null),

43 => array('name' => clienttranslate('Enterprise'),
    'i_demand_effect_1' => clienttranslate('${I demand} you transfer a top non-purple card with a ${icon_1} from your board to my board! If you do, draw and meld a ${age_4}!'),
    'non_demand_effect_1' => clienttranslate('You may splay your green cards right.'),
    'non_demand_effect_2' => null,
    'non_demand_effect_3' => null,
    'achievement_name' => null,
    'condition_for_claiming' => null,
    'alternative_condition_for_claiming' => null),
```
Some notes on the notation:
- Always set `achievement_name`, `condition_for_claiming`, and `alternative_condition_for_claiming` to null, since we only use these for special achievement cards.
- If you are transcribing a card with a compel effect, still put the text for the effect under `i_demand_effect_1`.
- The notation assumes that each card has at most one demand (or compel) effect and that it always appears before any non-demand effects. *Please tell me if you find a card violating this assumption!*
- In the transcribed cards, `${I demand}` is used to style the text in a special way. For compel effects, use `${I compel}`.
- To insert an image into the effect text denoting a particular age, use notation like `${age_4}`.
- To insert an image into the effect text denoting a particular resource icon, use the following notation:
    * Crown: `${icon_1}`
    * Leaf: `${icon_2}`
    * Lightbulb: `${icon_3}`
    * Tower: `${icon_4}`
    * Factory: `${icon_5}`
    * Clock: `${icon_6}`

**WARNING**: The cards are listed in a different order than we need to use in the internal implementation of the game. Use the icons in the `*_artifacts.png` files (found in https://github.com/micahstairs/bga-innovation/tree/main/misc/hexagon_icons) to help you determine the right card order. Then add 110 to that ID (since there are 110 cards in the base game).

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by jacksonmead** [comment]
For future issues similar to this, it might be useful to call out the fact that apostrophes need to be escaped and to include an example with an apostrophe (e.g., Clothing).

**Comment by jacksonmead** [comment]
Should we have one file per age, so people can work on these tasks in parallel (assuming that becomes possible at some point)? Or are you just planning to do one age at a time?
