### ISSUE TITLE
Manually test cards which might misbehave because bonus icons add points to the score 

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#603]
We should go through all of the cards and make a list of the cards which might misbehave when the score pile is empty but the player has points (because of bonus icons). We should manually test these cards (e.g. Optics).

**Comment by ultimatefiend** [comment]
I think optics is the only card that is affected by this.  I didn't see any others.  I tested it and it works correctly.

No card matches the criteria of the effect. <-- perfectly reasonable log message
It does not have a .
You draw and meld 3 Homing Pigeons. <-- no crown
You have to execute the non-demand effect.
kahliadev1 has 0 .
You have 5 .
You activate the dogma of 3 Optics with  as the featured icon.
You meld 10 MP3 from your hand. <-- adds 10 bonus points to your score
You draw 10 MP3.

**Comment by micahstairs** [comment]
Thanks for confirming! I feel comfortable closing this then.
