### ISSUE TITLE
Jet, Karaoke, Charitable Trust, and Stethoscope behave inconsistently when shared

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#621]
Stethoscope is supposed to make you draw an 8 iff you melded a blue card, but it doesn't behave properly when shared.  This can be seen on move 107/108 of https://studio.boardgamearena.com/table?table=414483 (both players draw an 8, even though only MadisonSilver0 should) and throughout https://studio.boardgamearena.com/gamereview?table=412783.

**Comment by ultimatefiend** [comment]
This is the same as #619.  This same issue will affect Karaoke as well.  Basically, sharing the effect corrupts the variable that stores the card (or color) of the card that was melded in the echo effect (or drawn by Charitable Trust).

**Comment by ultimatefiend** [comment]
I realized that if Jet were shared with someone (in a 3 person game for example), then the melded color would get corrupted by a similar mechanism.

**Comment by micahstairs** [comment]
I'll add a player-based auxiliary value. Right now the auxiliary value is shared between players, which causes the corruption.
