### ISSUE TITLE
Television Doesn't Check for Achievements of Same Value

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#623]
Television says "Choose a value and an opponent. Transfer a card of that value from their score pile to their board. If they have an achievement of the same value, achieve (if eligible) a card of that value from their score pile."  However, it doesn't check to see if the opponent has an achievement of the chosen value, and will instead always achieve (if eligible).

Reproductions:
https://studio.boardgamearena.com/gamereview?table=410693 (moves 16-19)
https://studio.boardgamearena.com/gamereview?table=419193 (moves 179-183)

**Comment by ultimatefiend** [comment]
Its hilarious because there is a comment to check for the achievement but it was never done.  Good find.
