### ISSUE TITLE
Achievements in the players area in reverse order

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#628]
This happens in reverse order right now:

![image](https://user-images.githubusercontent.com/11416698/193154472-ad3f8d8e-115c-4b25-874f-a270760f41af.png)

**Comment by ultimatefiend** [comment]
The above picture occurred when achieving the 1, then 2, then 3.

**Comment by ultimatefiend** [comment]
I think this is a regression and not an enhancement.  The achievements are no longer in the order in which they were achieved (as what happens in production).  Its now a somewhat random ordering.

**Comment by ultimatefiend** [comment]
I should also note that the special achievements are placed in the right order, but the numbered achievements are not.

**Comment by micahstairs** [comment]
Right you are! This regression was introduced a few weeks ago when I was working on support for multiple achievements of the same age.
