### ISSUE TITLE
Seed Drill and Ice Cream Misbehave on Empty Decks

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#630]
Seed Drill and Ice Cream, when used on an empty deck, will incorrectly send a card from the next nonempty deck to the achievements.  This also counts as a draw action and can end the game.
https://studio.boardgamearena.com/table?table=412814 (moves 71+)
https://studio.boardgamearena.com/table?table=416714 (moves 51+)

**Comment by ultimatefiend** [comment]
the issue is that those two cards are looking at ALL cards of the selected value and not just the base decks.
