### ISSUE TITLE
Change how gold stars are awarded at end of game

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#643]
See https://boardgamearena.com/bug?id=67958 and https://boardgamearena.com/bug?id=28575 for more details. Basically we want to give all winners 1 gold star and all other players 0 gold stars.

I'm lumping this into the Echoes release so that we can get some extra playtesting on it before it hits production.

**Comment by micahstairs** [comment]
The logic that needs to be updated is in stJustBeforeGameEnd.

**Comment by ultimatefiend** [comment]
I would make sure that team games don't end in a tie, but a joint win for the winning team (i.e. like werewolf or pandemic).

**Comment by micahstairs** [comment]
In a team game, both players on the winning team would get 1 gold star and both players on the losing team would get 0 gold stars.

We don't really have a way to tell BGA the difference between two players winning together vs two players being tied. Presumably BGA takes care of the difference automatically since it knows which players are on which teams?

**Comment by ultimatefiend** [comment]
that's not how it works at the moment.  a win is considered a tie for the winning team and not a team win.
