### ISSUE TITLE
Adjust automation logic in Oars when Echoes drawing rules make it so that the order makes a difference

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#646]
When Echoes is in play, there are certain situations where Oars can't simply transfer the cards in an arbitrary order. We need to reduce the automation in those situations.

**Comment by ultimatefiend** [comment]
Are there other cards where the order of drawing would be affected?

**Comment by micahstairs** [comment]
Off the top of my head, I don't think so. Oars has some custom automation for this special case (a series of transfers and draws). The general automation engine won't cause any problems.
