### ISSUE TITLE
Deodorant messes up drawing Echoes cards

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#650]
<img width="130" alt="Screen Shot 2022-10-02 at 12 26 23 PM" src="https://user-images.githubusercontent.com/15677300/193466752-d0ec2bf7-5bb2-48d5-b6ca-f72da7428f14.png">

See screenshot for log. I had cards in my hand and no Echoes. On the first action, the echo effect of Deodorant drew and melded an Echoes card, but then the dogma effect drew and melded a base card. And then on the second action of dogmaing Deodorant, both the echo effect and the dogma effect drew and melded base cards.

Here's the game: https://studio.boardgamearena.com/1/innovationdev?table=413464

**Comment by ultimatefiend** [comment]
Were there any echoes cards left?

**Comment by ultimatefiend** [comment]
The replay returns an error so I can't view it.  If you run out of echoes cards, then the base cards will be used instead (until the base cards run out of that age).

**Comment by jacksonmead** [comment]
OK, yeah, I can't replicate it, so I'm going to assume I just didn't pay attention to the fact that the age 3 echoes cards were gone. Sorry about that one!

**Comment by ultimatefiend** [comment]
No worries!
