### ISSUE TITLE
Almanac gives away information; scores Artifact cards

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#651]
1. My opponent did a dogma of Almanac, and I shared. The card in my forecast didn't have a bonus, so it automatically skipped that part of it, which revealed the information to my opponent that the card in my forecast doesn't have a bonus. (It happened that my opponent's forecast did have a card with a bonus, but I assume it works the same way for the actor and for any opponents who share.)

2. When my opponent scored a card because of Almanac, they scored an Artifact card instead of a base card.

Here's the game: https://studio.boardgamearena.com/1/innovationdev?table=416564&testuser=2359943

**Comment by ultimatefiend** [comment]
Yeah that's not right.  I don't know why it specifies "is_relic" as true.

                        self::executeDraw($player_id, $bonuses[0] + 1, 'score', false, true);

**Comment by micahstairs** [comment]
I put the fix for #1 in https://github.com/micahstairs/bga-innovation/pull/644 and @ultimatefiend is taking care of #2.
