### ISSUE TITLE
Email interacts strangely with purple cards

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#656]
Email's second dogma effect will sometimes fail to execute purple cards or execute a different card instead.

https://studio.boardgamearena.com/gamereview?table=412005 (moves 6+)
https://studio.boardgamearena.com/gamereview?table=411994 (moves 189+)

**Comment by ultimatefiend** [comment]
It looks like the nested execution doesn't execute a card (or its echo effects) if it has a demand effect.  I can look more into this later.

**Comment by ultimatefiend** [comment]
From the code :

                // "Execute all non-demand dogma effects on your lowest non-green top card. Do not share them."
                // TODO(ECHOES): There's multiple bugs here. Battleship Yamato's faceup age is 11, which breaks an
                // assumption that this code currently has. Also, purple is being exlcuded in the for loop. I propose
                // rewriting this using the countCardsInLocationKeyedByColor function and using an if statement instead
                // of a for loop.

**Comment by ultimatefiend** [comment]
Interestingly, we don't want to execute Yamato so probably excluding it would work just fine for this card.

**Comment by micahstairs** [comment]
Yamato is also a red card, not green. So yeah, I agree, we don't need to worry about that there.
