### ISSUE TITLE
Echo effects aren't executed when the top cards effects are executed (demand cards)

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#658]
![image](https://user-images.githubusercontent.com/11416698/193948679-cd1cc98e-1821-4ae0-9184-67b815f49637.png)

**Comment by ultimatefiend** [comment]
So this bug happens when there is a single demand effect and no other non-demand dogma effects.

If there is a demand card (e.g. flute) that also has a non-demand secondary effect, then the echo effect does trigger.

**Comment by micahstairs** [comment]
Have you replicated this bug since https://github.com/micahstairs/bga-innovation/commit/64c0a465db5718a3d8c90ecbd07110ee43fccdd1 was merged?

**Comment by ultimatefiend** [comment]
I just did it tonight in innovationdev.

**Comment by micahstairs** [comment]
Ah I replicated the bug too! Yeah this should be easy to fix. I see the problem.
