### ISSUE TITLE
Update "how to play" section and "Strategy tips" for Echoes

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#669]
We did this for Artifacts, but we need the same discussion about Echoes.  It needs to talk about the following topics:

1.  Forecast/foreshadowing/promotion
2. How the draw rules work
3. Bonus icons
4. Echo effects (also, how they affect cards on display)
5. Extra achievements (toothbrush, chopsticks, etc.) and how the score multiplier works

**Comment by micahstairs** [comment]
One of our BGA players (pitdood) is working on this (right in the innovationalpha wiki).

**Comment by micahstairs** [comment]
Done! https://en.doc.boardgamearena.com/Gamehelpinnovationalpha
