### ISSUE TITLE
Electrum Stater of Ephesus plus Echoes card

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#677]
Dogma Electrum Stater of Ephesus from board, with only base cards in hand. An Echoes card is drawn, and there are a bunch of errors.
<img width="167" alt="Screen Shot 2022-10-07 at 10 52 51 PM" src="https://user-images.githubusercontent.com/15677300/194684599-5858a984-4263-4f4c-ad06-aea00a615142.png">

**Comment by ultimatefiend** [comment]
the actual issue is executing an echo effect when you are dogma'ing an artifact from the display.
