### ISSUE TITLE
fermenting is broken

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#688]
It only appears to look at top cards for leaves.

**Comment by micahstairs** [comment]
Interesting! I was able to replicate it: 
![Uploading Screen Shot 2022-10-09 at 7.39.23 PM.png…]()

**Comment by micahstairs** [comment]
Interestingly, I couldn't replicate with Industrialization, even though they share a lot of the same logic: 
![Uploading Screen Shot 2022-10-09 at 7.40.58 PM.png…]()

**Comment by micahstairs** [comment]
Found the problem!
