### ISSUE TITLE
Email Executes Demand Effects

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#701]
Email seems to incorrectly execute demand effects of other cards; see https://studio.boardgamearena.com/gamereview?table=416176 (moves 250-254)

**Comment by micahstairs** [comment]
I wasn't able to replicate it:

<img width="1465" alt="Screen Shot 2022-10-14 at 7 54 50 AM" src="https://user-images.githubusercontent.com/7231485/195841049-db6beaab-2d68-46f2-98d1-60dcb0fb63e1.png">

From looking at your replay, it is also is behaving correctly. I think you saw the demand effect of the promoted card and got it confused with your dogma action.

<img width="1260" alt="Screen Shot 2022-10-14 at 7 58 39 AM" src="https://user-images.githubusercontent.com/7231485/195841650-3d0278cc-e82d-4e54-875c-26d913612501.png">

**Comment by ultimatefiend** [comment]
No, it executed the demand effect of photography and it shouldn't have.

**Comment by ultimatefiend** [comment]
actually, the message about Sudoku isn't totally right either.  It is being melded from forecast (Photography's echo effect) and not promoted.

**Comment by ultimatefiend** [comment]
This replicates the issue.

![image](https://user-images.githubusercontent.com/11416698/196087726-23b51741-c8f6-46d3-8e5a-e19f61acd842.png)

**Comment by micahstairs** [comment]
Ooh so my theory is that this happens whenever we call `executeNonDemandEffects` on a card that also has echo effects on it!
