### ISSUE TITLE
Democracy doesn't work if Clock's echo effect is visible

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#708]
This is very strange, but this board leads to no 8s being scored if a card is returned:

![image](https://user-images.githubusercontent.com/11416698/196079872-73f46682-1688-40a0-b934-66a23f5b51a8.png)

Note that the 8 that is there is from a previous attempt at scoring when clock's effect was not visible.

**Comment by ultimatefiend** [comment]
could this be problematic?

            // id 63, age 6: Democracy          
            case "63N1":
                if (self::getAuxiliaryValue() == -1) { // If this variable has not been set before
                    self::setAuxiliaryValue(0);
                }

Clock stores the colors with the maximum sizes in an array in auxiliary as well.

**Comment by ultimatefiend** [comment]
It might be as simple as resetting the auxiliary value between effects?

**Comment by micahstairs** [comment]
Oh so you think there might be a residual aux value from the echo effect? This is probably best solved in a generic way. I can take this!
