### ISSUE TITLE
Passing on the second dogma effect on Karaoke doesn't reset the card display

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#725]
![image](https://user-images.githubusercontent.com/11416698/197103011-b923ec75-db15-4079-9812-b82862cc2221.png)

This is after passing.  If you don't pass, everything resets correctly.

**Comment by ultimatefiend** [comment]
Karaoke is allowing me to select a 10 when executing the echo effect for some reason.

**Comment by micahstairs** [comment]
You can ignore the selection bug. That's already been fixed but hasn't been pushed to innovationdev.

**Comment by ultimatefiend** [comment]
The selection bug is still there...since you said its been pushed in chat.

![image](https://user-images.githubusercontent.com/11416698/197318615-703e6cdf-ce94-4fab-81cf-99538299b3d3.png)

**Comment by micahstairs** [comment]
The secondary issue is being tracked separately in https://github.com/micahstairs/bga-innovation/issues/728 now.
