### ISSUE TITLE
Telegraph Malfunctions When Passing

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#729]
When you don't choose a player, Telegraph will still prompt you to choose a color, then unsplay that color.
See https://studio.boardgamearena.com/gamereview?table=418929 (Move 234, MadisonSilver0's perspective).

**Comment by ultimatefiend** [comment]
I see the reason. I can fix this one.  It always has two steps even if the second part of the interaction is optional.
