### ISSUE TITLE
Mobility doesn't automate

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#735]
I dogmas Mobility, and my opponent had exactly two top non-red 9s (neither with factories), and it didn't automate. See screenshot, where no cards have been transferred yet.

<img width="923" alt="Screen Shot 2022-10-26 at 2 57 11 PM" src="https://user-images.githubusercontent.com/15677300/198112859-cf3f6b27-142a-442c-a0c3-6c30c38b084c.png">

**Comment by micahstairs** [comment]
Ah I see the problem. This interaction is implemented as two back to back interactions instead of a single one where two cards are  chosen. I can change that, which will also simplify the implementation.

**Comment by micahstairs** [comment]
So I tried the following:


```
// id 78, age 8: Mobility        
        case "78D1A":
            if (self::getGameStateValue('release_version') >= 2)  {
                // I demand you transfer the two highest non-red top cards without a factory from your board to my score pile! If you transferred any cards, draw an 8!
                $top_cards = self::getTopCardsOnBoard($player_id);
                $color_array = array();
                for ($age = 11; $age >= 1; $age--) {
                    foreach ($top_cards as $top_card) {
                        if ($top_card['faceup_age'] == $age && $top_card['color'] != 1 && !self::hasRessource($top_card, 5)) {
                            $color_array[] = $top_card['color'];
                        }
                    }
                    if (count($color_array) >= 2) {
                        break;
                    }
                }
                $options = array(
                    'player_id' => $player_id,
                    'n' => 2,
                    
                    'owner_from' => $player_id,
                    'location_from' => 'board',
                    'owner_to' => $launcher_id,
                    'location_to' => 'score',

                    'color' =>  $color_array
                );
                break;
            }
```

But I forgot about this edge case:
<img width="1219" alt="Screen Shot 2022-11-05 at 9 48 26 PM" src="https://user-images.githubusercontent.com/7231485/200150335-39b9e83d-8496-4844-8f16-cce0a509b3b8.png">

There's possible workarounds but it makes things more complicated. I'll probably punt this for now.

**Comment by ultimatefiend** [comment]
I think the best way to do this would be automatically score the cards when there are two uniquely high values...otherwise proceed with the individual transfers.

**Comment by micahstairs** [comment]
Oh good idea. I think that's only a small adjustment from the above.

**Comment by ultimatefiend** [comment]
I think the logic could be put in the first entry point for the demand action...that should work I think.
