### ISSUE TITLE
Add unbordered resource icons to spritesheet

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#74]
Right now we have two spritesheets for resource icons (one with borders and one without). Let's put these icons on the same spritesheet.

Details:
- Please base your work off of the `main-new-graphics` branch.
- The script to make the spritesheet with the bordered icons is found at https://github.com/micahstairs/bga-innovation/blob/main-new-graphics/misc/imagemagick_commands/bordered_square_icons.sh.
- The script to make the spritesheet with the unbordered icons is found at https://github.com/micahstairs/bga-innovation/blob/main-new-graphics/misc/imagemagick_commands/square_icon_spritesheet.sh.
- The unbordered icons can go in the last row of the merged spritesheet.
- Let's name the merged script `square_icon_spritesheet.sh`. Make sure the unused script and spritesheet are deleted.
- Let's also move the square icon images out of the `card_icon_borders` directory and put it in the `square_icons` directory.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the 
possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by normaljosh** [comment]
Closed with PR #90
