### ISSUE TITLE
Elevator and Barometer log messages

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#740]
kahliadev0 transfers 5 The pirate code from your forecast to your hand.

I shouldn't be able to see what card is transfered, and "your" should be "their" twice.

kahliadev0 chooses to transfer the 0s from all other score piles to their score pile.

"0s" should be the value chosen (in this case, it was 3s)

**Comment by ultimatefiend** [comment]
The biggest problem with barometer is that it informs the opponent of the card being transferred.

The 0s in the log message should have been 1s.
