### ISSUE TITLE
Score/forecast popup doesn't fit all of the cards when more than 5 cards are present

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#741]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/11416698/199882867-2bc50510-8581-45e3-a482-5324711741ff.png)

**Comment by micahstairs** [comment]
Does the score popup do the same thing? If so, I don't think this needs to be alpha-blocking or release-blocking.

**Comment by ultimatefiend** [comment]
The score pile does the same thing.

**Comment by micahstairs** [comment]
The next step will be to confirm whether this is happening in production or not.
