### ISSUE TITLE
Visual cues for when you're making a decision for a demand

### ISSUE THREAD

**Issue by jacksonmead** [micahstairs/bga-innovation#746]
Especially in turn-based games, it can be easy to think you're taking your turn rather than responding to a demand action from an opponent. Maybe we could have some visual cues (possibly as a player option?), such as turning the background behind the place where the text/buttons appear red and making the highlight on the selectable cards red as well.

**Comment by ultimatefiend** [comment]
color is tricky for those who are color blind...perhaps a symbol overlay would be better?  like a caution sign or something like that

**Comment by jacksonmead** [comment]
Would it be too tricky to do both? Or make it an either/or, if it's going to be a player option?
