### ISSUE TITLE
Duplicated Logs in Game Review

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#756]
On the game review pages (as opposed to the "archive/replay" pages), the game logs show multiple copies of each move from each player's perspective.
For example, see https://boardgamearena.com/gamereview?table=318026229

```
Move 213 :5:34:23 PM
You draw and meld 8 Rocketry.
You achieve Empire.
You return 7 Periodic Table from your display.
Sharing bonus.
You draw 8 Quantum theory.
MadisonSilver draws and melds 8 Rocketry.
MadisonSilver achieves Empire.
MadisonSilver returns 7 Periodic Table from his display.
Sharing bonus.
MadisonSilver draws a 8.
```

(This may be an issue on BGA's side, however it may be worth investigating anyway.)

**Comment by micahstairs** [comment]
That's just a quick of BGA! Nothing can be done there.
