### ISSUE TITLE
Special Achievements are not checked properly when two people are eligible at the same time

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#757]
This came up with Qtrie's issue:

https://boardgamearena.com/bug?id=75544

**Comment by micahstairs** [comment]
I believe the root cause is in `getActivePlayerIdsInTurnOrderStartingWithCurrentPlayer()`, likely with how we determine who the "current player" is.

Not going to lie, this will be annoying to fix (and test that it's working well), but it's worth doing.

**Comment by micahstairs** [comment]
I think this is best fixed by reverting the special achievement changes (https://github.com/micahstairs/bga-innovation/issues/764).

**Comment by micahstairs** [comment]
This is no longer worth doing now that we've changed the special achievement check back.
