### ISSUE TITLE
Road Building Automatically Melds card

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#773]
When a player has cards of different colors in hand, Road Building may automatically select one to meld.  See
https://studio.boardgamearena.com/table?table=426228 and https://boardgamearena.com/table?table=321401915 (Move ~50)

**Comment by micahstairs** [comment]
Looking at the code, I think the only other card this bug would affect is Ice Skates.

**Comment by micahstairs** [comment]
Never mind, Ice States wouldn't be affected. I think it's just Road Building.
