### ISSUE TITLE
Implement Artifact Age 1 Ark of the Covenant (ID 123)

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#82]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by ultimatefiend** [comment]
Detecting whether a top card is an artifact card might be a problem.  I think for now I can use the ID of the card to determine this.  It would be nice if the Database contained this information.

**Comment by micahstairs** [comment]
Using the ID is a reasonable workaround for now. Be sure to leave a TODO for me!
