### ISSUE TITLE
Transferring cards to a score pile causes a weird thing to happen

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#822]
https://boardgamearena.com/2/innovationalpha?table=325483199

This game had the situation after oars had executed, the interface didn't update.  The backend updated ok, but the front end did not.

After refreshing the page, then everything worked ok.

**Comment by ultimatefiend** [comment]
![image](https://user-images.githubusercontent.com/11416698/206922847-cb7e62f0-70f4-49c9-aaa4-805f61e3753f.png)

**Comment by micahstairs** [comment]
Katana just did the same (the cards were also going to the score pile).

**Comment by micahstairs** [comment]
"During notification transferedCardCannot read properties of undefined (reading '84799780')TypeError: Cannot read properties of undefined (reading '84799780') "

**Comment by micahstairs** [comment]
Okay I mostly tracked down the problem! Just trying to figure out the right fix.
