### ISSUE TITLE
Safari (Mobile on Iphone) has multiple graphical quirks

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#825]
See attached image:

![safari](https://user-images.githubusercontent.com/11416698/206943873-5d29897c-6750-469c-a3ef-4702e47a5792.png)

Note that the text is only half visible (including the required number of achievements to win).

The score and forecast is also cut off.  The score pile isn't displaying in two columns like the screenshots after the recent scoring spacing change.

**Comment by micahstairs** [comment]
Put another way, I don't have the experience necessary to get things fixed up for Safari. If we want to make progress on this, I think we need a dedicated developer to help with this. Lordmcfuzz would be a good candidate but he's been super busy lately.

**Comment by micahstairs** [comment]
Some of the latest changes should fix some of these issues. I'm going to close this and we can file new issues for specific problems.
