### ISSUE TITLE
Make visible flags count as an achievement if no opponent has more visible cards of the flag’s color

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#861]
From the rulebook:
> While a flag is visible, it counts as an achievement if no opponent has more visible cards of the flag’s color than you do.

**Comment by ultimatefiend** [comment]
Similar to fountains, I was thinking that there could be a flag achievement (one for each color) that would transfer to the player achievements if the conditions are met.  This would need to be checked when other special achievements are checked as tucking/melding/promoting can affect the location of the achievement.

**Comment by ultimatefiend** [comment]
In other words, two players could be duking it out if they have similar number of cards that are visible in the same color.

**Comment by micahstairs** [comment]
Good idea! When no one has the flag achievements, maybe we should store them near the special achievements area?

**Comment by ultimatefiend** [comment]
Yeah that sounds like a good idea.

**Comment by micahstairs** [comment]
Actually, if two people are tied then they both get the flag achievement. So we would need more than 1 of each color.

I might see if I can get this working without storing them in a visible location when they are unclaimed. I could just create them on the fly whenever we need them.

**Comment by micahstairs** [comment]
I accidentally pushed https://github.com/micahstairs/bga-innovation/commit/eb3c3af19aa20ce38307cfbf8e053298612a609b and https://github.com/micahstairs/bga-innovation/commit/6bc6b82c139377900e62ffdf9da10608c4b62eb4 without creating a PR.

<img width="287" alt="Screen Shot 2022-12-31 at 4 22 48 PM" src="https://user-images.githubusercontent.com/7231485/210177957-7888a590-c45c-49be-b532-0b4e01ade62c.png">
