### ISSUE TITLE
Make visible fountains count as an achievement

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#862]
From the rulebook:
> While a fountain is visible, it counts as an achievement.

**Comment by ultimatefiend** [comment]
I was thinking that we could display a fountain "card" in the player's achievements that currently counts as an achievement.  In reality, this is what they should have done in the print game as well to help track it.

**Comment by micahstairs** [comment]
Yes that seems like a good idea!

**Comment by micahstairs** [comment]
I counted 13 fountains, so this would be a lot of fountains to store near the special achievements area. Maybe I could stack them on top of each other like we do with decks.

**Comment by ultimatefiend** [comment]
not all of them will be visible at the same time.  At most, two will be visible when they are on top and one will be visible if tucked.

Either way, having a safe number of virtual cards is good.  We can also add a special tooltip for those achievements so they are obvious for new people.

**Comment by micahstairs** [comment]
I believe it's possible for all 13 to be visible if there are at least 3 players in the game.

**Comment by ultimatefiend** [comment]
ahh ok

**Comment by micahstairs** [comment]
I accidentally pushed https://github.com/micahstairs/bga-innovation/commit/eb3c3af19aa20ce38307cfbf8e053298612a609b and https://github.com/micahstairs/bga-innovation/commit/6bc6b82c139377900e62ffdf9da10608c4b62eb4 without creating a PR.

<img width="287" alt="Screen Shot 2022-12-31 at 4 22 48 PM" src="https://user-images.githubusercontent.com/7231485/210177957-7888a590-c45c-49be-b532-0b4e01ade62c.png">
