### ISSUE TITLE
When endorsing the order of actions in the log is wrong

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#874]
![image](https://user-images.githubusercontent.com/11416698/210931930-0c72a4b5-7fcc-4719-b781-cf31e3e2c4e0.png)

The tuck shouldn't happen before deciding to endorse.

**Comment by micahstairs** [comment]
Where would you like to see the log message moved to? It's not going to be the easiest to move it.

**Comment by ultimatefiend** [comment]
ok, if its not easy, then maybe it could be clearer that the tucking is paying for the endorsement then?

**Comment by ultimatefiend** [comment]
Anyway, the ordering is strange, but I don't think this is critical.

**Comment by ultimatefiend** [comment]
another thought...the selection interaction could select a card specifically (with the recent array function that was added for echoes) instead of selecting a card to tuck directly.  This would allow the log message to be put in the correct order before the actual transfer occurs.

**Comment by micahstairs** [comment]
Where do you want the message to appear? I can find the simplest way to make that happen.

**Comment by ultimatefiend** [comment]
the tuck message should be after the endorsement confirmation message.  that would be in line with the rules.

**Comment by micahstairs** [comment]
Before or after the resource icons are printed?

**Comment by ultimatefiend** [comment]
before the "you have 5 crowns" message in the log above since the tucked card can impact the sharing/vulnerability.

**Comment by ultimatefiend** [comment]
as soon as the card is selected, the endorsement has begun so there should be an opportunity to throw that log message?
