### ISSUE TITLE
The flag/fountain achievements come from the top left of the screen when they are achieved (temporarily)

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#889]
Its a little weird to see the flag achievements appear from outer space while playing. :)

Its just a little weird and not a major thing.  If it were to materialize out of nothing (and not move from somewhere else) that would be better if that is possible.

**Comment by micahstairs** [comment]
This is almost at the top of my TODO list now! I have some ideas for how to fix this.
