### ISSUE TITLE
Put colorblind indicators right on top of card backgrounds

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#89]
I know we've moved the colorblind indicators around quite a bit, but now that most of the spritesheets are being locked down, I've decided it makes most sense to place them right on the card backgrounds themselves.

Details:
- Please base your changes on the `main-new-graphics` branch.
- Don't worry if the colorblind indicators aren't perfectly positioned on the card backgrounds (it's easy enough for me to tweak the position a bit)
- Make sure you do this using ImageMagick. You can add the commands right to https://github.com/micahstairs/bga-innovation/blob/main-new-graphics/misc/imagemagick_commands/crop_backgrounds.sh.
- You can find the colorblind indicator shapes in https://github.com/micahstairs/bga-innovation/tree/main-new-graphics/misc/card_shapes

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by normaljosh** [comment]
Closed with PR #90
