### ISSUE TITLE
Create a "Meld from Bottom" mechanism

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#92]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

Seikilos Epitaph has a dogma that forces the bottom card of a pile to be melded on top.  I've tried a number of different methods to accomplish this, but every attempt thus far has led to really bizarre behavior.

First attempt was to try to manually change the positions of the cards, but there doesn't appear to be a simple way to do this.  "rearrange" offers a possible solution here, but Micah advised to stay away.

Second attempt was to transfer the card from the bottom to "revealed" and then transfer that to the top of the pile.  However, that isn't possible right now.  There is no transition from board to revealed.

Third attempt was to put the card in hand first and that caused all sorts of crazy issues to come up with the displayed board state.

So, I'm punting for now.  Here is the code that I had in its simplest state:

            // id 125, Artifacts age 2: Seikilos Epitaph
            case "125N1":
                // "Draw and meld a 3"
                $melded_card = self::executeDraw($player_id, 3, 'board');
                $melded_color = $melded_card['color'];
                $max_position = $melded_card['position'];
                
                // "Meld your bottom card of the drawn card's color.
                $bottom_card = self::getBottomCardOnBoard($player_id, $melded_color);
                
                self::transferCardFromTo($bottom_card, $player_id, 'hand');
                self::transferCardFromTo($bottom_card, $player_id, 'board');
                self::checkAndPushCardIntoNestedDogmaStack($bottom_card); // "Execute its non-demand dogma effects. Do not share them."

                break;

and the DB entry:

(125, 2, 0, 2, 2, 2, 0, 2, 0, 'deck', 0, NULL, FALSE),

**Comment by jacksonmead** [comment]
Note that whatever solution happens will need to count as a meld for when we implement Figures, for the "If you would meld..." karmas.

**Comment by micahstairs** [comment]
That's a great point! Thanks for flagging that.

**Comment by ultimatefiend** [comment]
For what its worth, every single "meld" action (like optics) would need to have a keyword added (like the score_keyword) to differentiate between a transfer (like skyscrapers) and a meld dogma.

**Comment by micahstairs** [comment]
Yeah I was also thinking we might want to add a 'meld_keyword' field later!

**Comment by micahstairs** [comment]
I played around with a few different approaches and found out that we can simply do `self::transferCardFromTo($bottom_card, $player_id, 'board');`.

```
            // id 125, Artifacts age 2: Seikilos Epitaph
            case "125N1":
                // "Draw and meld a 3"
                $melded_card = self::executeDraw($player_id, 3, 'board');
                
                // "Meld your bottom card of the drawn card's color"
                $bottom_card = self::getBottomCardOnBoard($player_id, $melded_card['color']);
                self::transferCardFromTo($bottom_card, $player_id, 'board');

                // "Execute its non-demand dogma effects. Do not share them."
                self::checkAndPushCardIntoNestedDogmaStack($bottom_card);
                break;
```
