### ISSUE TITLE
Television leads to an error

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#928]
This was executed with Satellites so I'm not sure that's related.

This is the error:

Unexpected error: Unhandled case in notifyWithTwoPlayersInvolved(): 'score->board' (reference: GS2 01/02 02:38:50)

**Comment by ultimatefiend** [comment]
it's blocking this game from continuing:

https://boardgamearena.com/2/innovationalpha?table=340677247

**Comment by micahstairs** [comment]
Just pushed a fix!
