### ISSUE TITLE
Helicopter symbol detection should be amended

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#939]
Helicopter (age 9 red echo card) doesn't detect for symbols that aren't base icons and the player does not have the option to match other symbol types (but should).

This is a bug in the card that should be resolved.

**Comment by ultimatefiend** [comment]
Other symbol types would be the city special symbols and bonuses (exact number only).

**Comment by micahstairs** [comment]
For reference, here's the ruling by Carl: https://boardgamegeek.com/thread/1872362/article/40784224#40784224.

**Comment by micahstairs** [comment]
This was fixed a while ago.
