### ISSUE TITLE
Can't select a pile on other player boards without transferring the top card

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#95]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

In the base set, this isn't a feature.  There are a few cards that touch other people's boards (non-demand) like Fission and Bioengineering, but they both involve transferring the card elsewhere.

So, adding a mechanism for selecting the card would be helpful.  I imagine it will be helpful in the future too.  In fact, Self Service could use this feature without the workaround that's currently there.

Here is the code for Cyrus Cylinder thus far:

       // id 134, Artifacts age 2: Cyrus Cylinder
        case "134N1A":
            // "Choose any other top purple card on any player's board."
             $options = array(
                'player_id' => $player_id,
                'n' => 1,
                'can_pass' => false,
                
                'owner_from' => 'any player',
                'location_from' => 'board',
                'owner_to' => -1, // Nothing is to be done with that card
                'location_to' => 'board',

                'color' => array(4),
                'not_id' => 134 /* Cyrus Cylinder */
            );
            break;

        // id 134, Artifacts age 2: Cyrus Cylinder
        case "134N1B":
            // "Splay left a color on any player's board"
             $options = array(
                'player_id' => $player_id,
                'n' => 1,
                'can_pass' => false,
                
                'owner_from' => 'any player',

                'splay_direction' => 1
            );
            break;

and this:

                // id 134, Artifacts age 2: Cyrus Cylinder
                case "134N1A":
                    if ($n > 0) { // Unsaid rule: another purple top card must be selectable
                        $selected_card = self::getCardInfo(self::getGameStateValue('id_last_selected'));
                        self::checkAndPushCardIntoNestedDogmaStack($selected_card); // "Execute its non-demand dogma effects.  Do not share them."
                    }
                    break;

(134, 1, 2, 4, 0, 3, 3, 4, 3, 0, 'deck', 0, NULL, FALSE);

**Comment by micahstairs** [comment]
Thanks for filing this issue! I can definitely look at adding the requested feature. I will need to be careful that I don't break in-progress games which are using the "Self Service" card. However, I expect the odds of the cards currently being played at the moment that we deploy the changes to be quite low, so the risk isn't too bad either way.

**Comment by micahstairs** [comment]
I think I'm going to implement this using `'location_to' => 'none'`. When looking through the code, this seemed like the simplest and cleanest solution.

**Comment by ultimatefiend** [comment]
That sounds like a good solution!
