### ISSUE TITLE
Expansions add more required achievements

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#99]
**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

When expansions are included, the required number of achievements are increased by 1 per expansion that is included.

Additionally, the rules allow for an optional rule where an extra achievement is required for victory.  This can lead to longer and more challenging games.  This feature is supported on isotropic today.

**Comment by micahstairs** [comment]
I wasn't aware of that optional rule, but let's not worry about that for the time being. That could be a separate game option that is added later.

I should note, however, that this work is blocked by a game option for the expansion (right now we don't know whether players want to play with Artifacts or not).
